== Introduction

Metadata records play a very important role in the WIS by providing the information that will allow WIS users to discover, access and retrieve products.  Metadata records have to adhere to standards (such as standard vocabularies and schemas) to ensure product definition homogeneity and make systems interoperable. There are a number of metadata standards that address the needs of meteorological and hydrological communities. The WIS discovery metadata standard (for dataset discovery catalogues) is called WMO Core Metadata Profile 1.3 (WCMP 1.3). It is a profile of the International Organization for Standardization (ISO) 19115:2003 metadata standard (_ISO 19115:2003 Geographic information - Metadata_), with its associated ISO 19139 XML schema implementation. ISO 19115 is a complex standard, thus both organizational and subject expertise may be required to create high-quality ISO 19115 metadata records that clearly describe an object in the context in which it is used.

This part of the Guide is intended for metadata authors and product or infrastructure specialists who create WCMP 1.3 metadata records for making their datasets discoverable within the WIS catalogue(s). It will also assist those who wish to create high-quality WIS metadata records for data that will be ingested and distributed by a GISC.

The WCMP 1.3 is defined in Appendix C of the Manual on WMO Information Systems (WMO-No. 1060): https://library.wmo.int/index.php?lvl=notice_display&id=9254.  

The WCMP homepage on WMO Community Platform the contains resources that complements this guide, such as templates, examples, links to validation tools and additional guidance: https://community.wmo.int/activity-areas/wis/wcmp.  
