== WIS Product Categories

Two categories of information (and corresponding transport protocols) are used in WIS catalogues:

=== Routinely distributed information (GTS-delivered information)

This is mainly, but not exclusively, traditional WMO bulletins.

This category is governed by the set of regulations described in the Manual on the Global Telecommunication System (WMO-No. 386). It includes the bulletin header (abbreviated header line) which identifies a bulletin like ISMS01 AMMC, and a file naming convention.

Metadata records for GTS bulletin datasets need to follow a set of additional rules and require an understanding of the GTS regulations. Non-bulletin files can also be distributed via the GTS. 

The most notable feature is the store-and-forward delivery mechanism for bulletins and other data on the GTS. This is the reason why there may be no URL for a bulletin - once a bulletin is delivered, it is not retained for later reference.

Today, GISCs serve bulletins issued in the past 24 hours, but the common practice is still that a metadata record for bulletins does not include the access URL(s). Global Information System Centres do, however, add links to search results pointing to information that is in their cache.

=== Information that is not routinely distributed (non-GTS-delivered information)

This can include both data stored as files and data as services.

This category includes datasets that are described and searchable in the WIS catalogues but are served by different responsible organizations, via their own infrastructure and data access services. WCMP 1.3 metadata records for this second category have to follow a minimum set of rules to be compliant with the standard. This is a subset of the rules that apply to routinely distributed information.

Typically, these metadata records include a URL for access to the data.

This part of the Guide provides extensive support for creating the different parts of a metadata record, for both non-GTS and GTS-delivered datasets. When necessary, an additional section for creating metadata records for GTS bulletins has been added in each information category (for example, the product information abstract).

