== WMO Core Metadata Profile - Validation Tools

Metadata publishers are required to ensure that created metadata records conform to relevant technical specifications. For example, XML documents need to be well-formed, validated against the schema, and compliant with other requirements imposed by the specifications. 

A set of ISO and WCMP validation tools can be used to ensure that a created WCMP record is correctly formatted (syntactically and semantically) and can be ingested by a GISC. 

In most cases, a metadata author will validate a metadata record using a validation tool. That tool may be either a web service or locally installed software. Usually, metadata records to be validated may be stored either locally or at a URL accessible to the validation tool.

Online validation services can automatically evaluate the content of the metadata in terms of completeness, accuracy and conformance. 

It is recommended to test the metadata with one of the available tools listed on the WCMP homepage. It is also always possible to seek assistance from your principal GISC. 
