== GENERATING METADATA RECORDS COMPLIANT WITH THE WMO CORE METADATA PROFILE 

This part of the Guide is intended to help product specialists create WIS metadata records that are compliant with the WCMP 1.3. It provides practical guidance on key information needed in WCMP metadata creation (such as describing how and where to insert the necessary product information into a template record, and the WIS specific information required in the XML metadata record), while abstracting (as much as possible) the WCMP standard, the ISO 19115 standard and its XML mapping (ISO 19139).

Section 5.8 below defines a set of recommendations for adding each individual piece of information regarding a product (for example, title, abstract, party responsible for the product, access to the product).

Although metadata authors will not normally need to work with XML directly because the GISC provides form-based editing tools, this part of the Guide uses an approach based on an XML template. A metadata author who needs to work directly with XML should use a copy of the template XML record(s) (see section 5.1) in conjunction with this part of the Guide, especially section 5.8. 

The template-based approach allows a person without any knowledge of ISO 19115 to create an XML WCMP metadata record populated with the key information needed to make the record easily searchable and accessible within a WIS portal.

The template files can also be used as the foundation for building a Web-based editing tool where the user completes a web form, and the content is used to overwrite the placeholders and create the final WCMP 1.3 compliant metadata record. Such tools are provided by the GISCs.

