== Necessary Information to Create a Metadata Record Compliant with the WMO Core Metadata Profile

This section describes the information needed to build a meaningful metadata record. For each individual component, the following elements are provided:

- *Necessity:* Whether the component is mandatory (conditionally), highly recommended or optional, within WCMP 1.3; 
- *Template value:* The template XML record's placeholder value that is to be replaced including the revelance of the element (see section 5.7 - template-based principle);
- *Information:* A summary of the type of information (from the metadata creator) that should replace the placeholder;
- *Category:* An overarching classification of the element;
- *XPath:* Its location within the WCMP XML metadata record; 
- An example of XML for that component, with content instead of placeholders.

The metadata creator should, when reading the documentation, open the relevant metadata template record and find the placeholder(s) to be replaced by the relevant product information.

For each component, this part of the Guide describes what is generally required for a product, followed, where relevant, by details of what is required in a WCMP record for GTS bulletin-specific metadata.

=== Product information

==== Product title

.Product title
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
a|
ADD-PRODUCT-TITLE*M +
ADD-ALTERNATE-TITLE*O

|Information
|Product name

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:citation/*/gmd:title/*/text()` (line 45 in annex)

|===

The product title and the product abstract are the two most relevant elements in the WCMP metadata record, in the context of WIS metadata catalogues, as they appear in search results and on the product description page. They assist users searching for relevant products and should, therefore, focus on the product's key characteristics.

The title should be as specific about the product as possible. If the product contains only one parameter, for instance, this can be stated in the title. However, if the product contains many parameters, the title should be more general and the parameters should be listed elsewhere in the metadata record (the abstract and/or the keywords). The title of a satellite product containing one main data parameter will typically describe that parameter and from which instrument or instrument type it originates, for instance, "AMSR-2 Sea Surface Temperature" or "SLSTR L1B radiances and brightness temperatures".


====== Example: Product title
```xml
<gmd:identificationInfo>
   <gmd:MD_DataIdentification>
      <gmd:citation>
         <gmd:CI_Citation>
            <gmd:title>
               <gco:CharacterString>AMSR-2 Sea Surface Temperature</gco:CharacterString>
            </gmd:title>
            <gmd:alternateTitle>
               <gco:CharacterString>
               AMSR-2 Sea Surface Temperature SST
               </gco:CharacterString>
            </gmd:alternateTitle>
           . . . . . .
         </gmd:CI_Citation>
      </gmd:citation>
      . . .. .
   </gmd:MD_DataIdentification>
</gmd:identificationInfo>
```

===== Title for GTS bulletins

The title for a GTS bulletin should also aim to be specific about the product, describing as much as possible the type of observation and including the bulletin code or identifier and original distributor (for example, EREH RSMC Erehwon).

For instance: 

====== Example: Title for GTS bulletins
```xml
<gmd:identificationInfo>
    <gmd:MD_DataIdentification>
      <gmd:citation>
        <gmd:CI_Citation>
          <gmd:title>
            <gco:CharacterString>Sea level observations data [SZPS01] for the South Pacific area. CREX encoded. Every 3 minutes or as required (available from AMMC). 
</gco:CharacterString>
          </gmd:title> …
```

==== Product abstract

.Product abstract
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
a|
ADD-PRODUCT-ABSTRACT*M

|Information
|Abstract describing the product

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:abstract/*/text()` (line 45 in annex)

|===

The product abstract is important in the context of WIS catalogues, as it is part of the product information that is presented in the search results page. It should describe aspects that the data producer judges as important and that will help potential users understand the key characteristics and nature of the product, thus enabling them to quickly assess the suitability of that product for their needs.

In order to have a more coherent and homogeneous set of product descriptions on the WIS, it is recommended to use the structure of abstract described below. Product abstracts that have a similar structure will help users who are comparing related and different data products.

The product abstract should complement the title by more accurately explaining the content of the product, and should provide further detail, where appropriate, describing the product and in particular the source of the data (such as the instrument type or model when applicable), the coverage, the production frequency (hourly, every 3 minutes, etc.), the data processing level (near real time, derived, quality controlled), the available formats and the data access services when relevant.

Below are typical abstracts and titles for:

* A numerical weather prediction (NWP) product:
**  Title: Copernicus Atmosphere Service MACC-IFS near-real-time 5-day forecast of global black carbon aerosol concentration;
** Abstract: This service provides pre-operational daily forecasts (up to 5 days) of global black carbon aerosol, using the IFS-LMD aerosol model. The product contains black carbon aerosol mixing ratios at 60 model levels. There are two forecasts per day, with base times of 00:00 UTC (5 day forecast) and 12:00 UTC (1-day forecast). Forecast steps are available at 3 hourly intervals and the spatial resolution is 0.75x0.75 degree. The forecast fields are generated in GRIB.
* A satellite observation product:
** Title: IASI Atmospheric Temperature, Water Vapour and Surface Skin Temperature–Metop;
** Abstract: The Atmospheric Temperature, Water Vapour and Surface Skin Temperature (TWT) product contains the vertical profiles of atmospheric temperature and humidity, with a vertical sampling at 101 pressure levels, and surface skin temperature. The vertical profiles are retrieved from the IASI sounder measurements (IASI L1C product) together with collocated microwave measurements (AMSU & MHS 1B) when available. The main objective of the Infrared Atmospheric Sounding Interferometer (IASI) is to provide high resolution atmospheric emission spectra to derive temperature and humidity profiles with high spectral and vertical resolution and accuracy. Additionally, it is used for the determination of trace gases, as well as land and sea surface temperature, emissivity and cloud properties. The products are provided at the single IASI footprint resolution (which is about 12 km with a spatial sampling of about 25 km at Nadir). The quality and yield of the vertical profiles retrieved in cloudy instantaneous fields of view (IFOVs) are strongly related to the cloud properties in the IASI Cloud Parameter (CLP) product and the availability of collocated microwave measurements.

* GTS bulletin
** Title: SMPS02 SYNOP reports (pressure, temperature and wind) – South Pacific area; available from NZKL (WELLINGTON/KELBURN) at 00, 06, 12 and 18 UTC;
** Abstract: This bulletin dispatches synoptic data (pressure, temperature and wind) every 6 hours, starting at 0000 UTC. The bulletin includes reports from the following stations: 91823 (NIUE AERO AWS) and 91962 (PITCAIRN ISLAND AWS).
** Data type: Surface data - Main synoptic hour - South Pacific area. 
** Actual data parameters sent include: pressure, pressure reduced to mean sea level, 3-hour pressure change, characteristic of pressure change (increasing or decreasing), temperature (dry-bulb and dewpoint), wind direction and wind speed.
** Format: FM 12 (SYNOP - Report of surface observation from a fixed land station (see the Manual on Codes (WMO-No. 306)).

** The SMPS02 TTAAii Data Designators decode as: 
*** T1 (S): Surface data; 
*** T2 (M): Main synoptic hour;
*** A1A2 (PS): South Pacific area.
*** (See the Manual on the Global Telecommunication System (WMO-No. 386), Attachment II.5.) 

==== Metadata responsible party

.Metadata responsible party
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
a|
ADD METADATA CONTACT ORGANISATION NAME*M + 
ADD ADDRESS STREET*O + 
ADD CITY*O + 
ADD REGION*O + 
ADD POSTCODE*O + 
ADD COUNTRY*O + 
ADD EMAIL ADDRESS*HR + 
ADD ORGANISATION WEBSITE*O + 

|Information
|Party responsible for the created metadata record

|Category
|Administrative information

|XPath
a|`/gmd:MD_Metadata/gmd:contact/gmd:CI_ResponsibleParty`

|===

This element describes the contact details (address, telephone, email) of the party responsible for the metadata. For example:

====== Example: Metadata responsible party
```xml
<gmd:MD_Metadata>
   ….. .. .. . 
   <gmd:contact>
      <gmd:CI_ResponsibleParty>
          <gmd:organisationName>
              <gco:CharacterString>EUMETSAT</gco:CharacterString>
          </gmd:organisationName>
          <gmd:contactInfo>
              <gmd:CI_Contact>
                  <gmd:address>
                      <gmd:CI_Address>
                          <gmd:deliveryPoint>
                              <gco:CharacterString>EUMETSAT Allee 1</gco:CharacterString>
                          </gmd:deliveryPoint>
                          <gmd:city>
                              <gco:CharacterString>Darmstadt</gco:CharacterString>
                          </gmd:city>
                          <gmd:administrativeArea>
                              <gco:CharacterString>Hessen</gco:CharacterString>
                          </gmd:administrativeArea>
                          <gmd:postalCode>
                              <gco:CharacterString>64295</gco:CharacterString>
                          </gmd:postalCode>
                          <gmd:country>
                              <gco:CharacterString>Germany</gco:CharacterString>
                          </gmd:country>
                          <gmd:electronicMailAddress>
                              <gco:CharacterString>ops@eumetsat.int</gco:CharacterString>
                          </gmd:electronicMailAddress>
                      </gmd:CI_Address>
                  </gmd:address>
                  <gmd:onlineResource>
                      <gmd:CI_OnlineResource>
                          <gmd:linkage>
                              <gmd:URL>http://www.eumetsat.int</gmd:URL>
                          </gmd:linkage>
                      </gmd:CI_OnlineResource>
                  </gmd:onlineResource>
              </gmd:CI_Contact>
          </gmd:contactInfo>
          <gmd:role>
              <gmd:CI_RoleCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="pointOfContact">pointOfContact</gmd:CI_RoleCode>
          </gmd:role>
      </gmd:CI_ResponsibleParty>
  </gmd:contact>
```

==== Product responsible party

.Product responsible party
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
a|
ADD PRODUCT RESPONSIBLE PARTY ORGANISATION SHORTNAME*M + 
ADD PRODUCT RESPONSIBLE PARTY EMAIL*HR

|Information
|Organization responsible for the product described in the metadata record

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:pointOfContact/gmd:CI_ResponsibleParty`

|===

This element contains the contact details of the organization responsible for the product. At least a name and an e-mail address are required, and the role should be `"pointOfContact"`.

====== Example: Product responsible party
```xml
<gmd:MD_Metadata>
   ….. .. .. . 
 <gmd:identificationInfo>
   <gmd:MD_DataIdentification>
      <gmd:citation>
       .. .. .. .. .
      </gmd:citation>
      .. . . . . . . 
      <gmd:pointOfContact>
       <gmd:CI_ResponsibleParty>
          <gmd:organisationName>
              <gco:CharacterString>EUMETSAT</gco:CharacterString>
          </gmd:organisationName>
          <gmd:contactInfo>
              <gmd:CI_Contact>
                  <gmd:address>
                      <gmd:CI_Address>
                          <gmd:country>
                              <gco:CharacterString>Germany</gco:CharacterString>
                          </gmd:country>
                          <gmd:electronicMailAddress>
                              <gco:CharacterString>ops@eumetsat.int</gco:CharacterString>
                          </gmd:electronicMailAddress>
                      </gmd:CI_Address>
                  </gmd:address>
                  <gmd:onlineResource>
                      <gmd:CI_OnlineResource>
                          <gmd:linkage>
                              <gmd:URL>http://www.eumetsat.int</gmd:URL>
                          </gmd:linkage>
                      </gmd:CI_OnlineResource>
                  </gmd:onlineResource>
              </gmd:CI_Contact>
          </gmd:contactInfo>
          <gmd:role>
              <gmd:CI_RoleCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/
resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="pointOfContact">
pointOfContact</gmd:CI_RoleCode>
          </gmd:role>
        </gmd:CI_ResponsibleParty>
    </gmd:pointOfContact>
```

==== Temporal extent

.Temporal extent
[cols="1,1"]
|===

|Necessity
|Optional for WCMP 1.3

|Template value
a|
ADD TEMPORAL INFORMATION*HR + 
ADD TEMPORAL INFORMATION startDate*HR + 
ADD TEMPORAL INFORMATION endDate*HR +
ADD TEMPORAL INFORMATION duration*O 

|Information
|Time period to which the product applies

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:extent/*/gmd:temporalElement/*/gmd:extent/`

|===

This element describes the period of time to which the product applies. Where the product has a clear start and end date, and where the entire set of data is available, the specific start date and end date should both contain a date or date and time. The date information is constructed as `YYYY-MM-DD`, while the date and time information is constructed as `YYYY-MM-DDTHH:MM:SSZ` (for UTC time) as in `2016-04-17T13:42:54Z`. In the examples below, the start and end dates are indicated as `beginPosition` and `endPosition`. For a TimePeriod, the begin and end positions must always be included whereas duration is optional. 

The encoding of a duration as `[(- or +) PnYnMnDTnhnmns]` allows the expression of time intervals such as: a number of years (nY), and/or months (nM), and/or days (nD), or hours (nh), or minutes (nm), or seconds (ns), where “n” represents a number. For example, a duration of 4 hours is expressed as `P0Y0M0DT4h0m0s` or `PT4h`. Note that duration can be expressed using either the long form (e.g.: `P0Y5M0DT0h0m0s`) or the short form, but the latter must include `"T"` for intervals of hours, minutes or seconds (e.g.: `P5M` is 5 months, `PT5m` is 5 minutes). 

Here are some examples of temporal extents whose meaning is described in the following paragraphs:

.Example temporal extents
[cols="1,1"]
|===

|[DateX] to [DateY]
a|
e.g.: +
`beginPosition: 2005-10-01` + 
`endPosition: 2014-10-20`

|[DateX] to [now]
a| e.g.: +
`beginPosition: 2005-10-01` + 
`endPosition: now`

|[Now] plus [period]
a| e.g.: + 
`beginPosition: now` + 
`endPosition: after` +
`duration: P7D (short)` or `duration: P0Y0M7DT0h0m0s (long)` (+7 days)

|===

Where it is not possible to accurately capture the time period in the `temporalExtent` (using the start date, end date and duration), record details that are as close as possible, and then explain the period in words, using the description field.

The following example shows a dataset with a known start date and a known end date:

====== Example: [DateX] to [DateY]
```xml
<gmd:temporalElement>
  <gmd:EX_TemporalExtent id="boundingTemporalExtent">
    <gmd:extent>
      <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
        <gml:beginPosition>2005-10-01</gml:beginPosition>
        <gml:endPosition>2014-10-20</gml:endPosition>
      </gml:TimePeriod>
    </gmd:extent>
  </gmd:EX_TemporalExtent>
</gmd:temporalElement>
```

It is also possible to describe an ongoing dataset with a known start date, but no known end date. In that case, the `endPosition` should contain the attribute `indeterminatePosition="now"`. For instance, where a dataset is from 2005-10-01 onwards, it would be encoded as follows:

====== Example: [DateX] to [now]
```xml
<gmd:temporalElement>
  <gmd:EX_TemporalExtent id="temporalExtent">
    <gmd:extent>
      <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
        <gml:beginPosition>2005-10-01</gml:beginPosition>
        <gml:endPosition indeterminatePosition="now"/>
      </gml:TimePeriod>
    </gmd:extent>
  </gmd:EX_TemporalExtent>
</gmd:temporalElement>
```

For a `TimePeriod`, the begin and end positions must always be included whereas duration is optional. For more information on encoding of duration, see https://en.wikipedia.org/wiki/ISO_8601#Durations.

The `EX_TemporalExtent` options for a `TimePeriod` hence include `beginPosition`, `endPosition` and `duration`, e.g.:

. `<gml:beginPosition> ..   …  …</gml:beginPosition>`
. `<gml:endPosition> ..   …  …</gml:endPosition>`
. `<gml:duration> ..   …  …</gml:duration>`

For a dataset that is ongoing (that is, new data are continuously produced) but for which only the latest file is available (that is, data is only ever available for a rolling window of time), the `TemporalExtent` should reflect the period covered by the available data, in this case, the period covered by the latest file.

For instance, where only the latest file is ever available, and the latest file is a forecast for the next 7 days, it would be encoded as follows:

====== Example: [Now] plus [period]
```xml
<gmd:temporalElement>
   <gmd:EX_TemporalExtent>
      <gmd:extent>
         <gml:TimePeriod>
            <gml:description>Next 7 days only</gml:description>
            <gml:beginPosition indeterminatePosition="now"/>
            <gml:endPosition indeterminatePosition="after"/>
            <gml:duration>P7D</gml:duration>
         </gml:TimePeriod>
     </gmd:extent>
   </gmd:EX_TemporalExtent>
</gmd:temporalElement>
```

==== Geographical information

.Geographical information
[cols="1,1"]
|===

|Necessity
|Conditional. It is mandatory for WCMP 1.3, if the data is geographical

|Template value
a|
(ADD-GEOSPATIAL-INFORMATION*C) + 
ADD BBOX VALUE WEST*M MW +
ADD BBOX VALUE EAST*M MW +
ADD BBOX VALUE SOUTH*M MW +
ADD BBOX VALUE NORTH*M MW

|Information
|Geographical coverage of the product, as a bounding box latitude and longitude

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:extent/*/gmd:geographicElement/gmd:EX_GeographicBoundingBox/*/*/text()` [having 4 elements]

|===

The geographical area covered by the product is described as a bounding box with latitude and longitude in decimal degrees. 

The following example shows the XML for bounding box information of a dataset:

====== Example: Geographical information
```xml
<gmd:geographicElement>
   <gmd:EX_GeographicBoundingBox id="boundingGeographicBoundingBox">
      <gmd:westBoundLongitude>
         <gco:Decimal>-180</gco:Decimal>
      </gmd:westBoundLongitude>
      <gmd:eastBoundLongitude>
         <gco:Decimal>180</gco:Decimal>
      </gmd:eastBoundLongitude>
      <gmd:southBoundLatitude>
         <gco:Decimal>-90</gco:Decimal>
      </gmd:southBoundLatitude>
      <gmd:northBoundLatitude>
         <gco:Decimal>90</gco:Decimal>
      </gmd:northBoundLatitude>
   </gmd:EX_GeographicBoundingBox>
</gmd:geographicElement>
```

Bounding boxes that cross the 180 degree meridian can be differentiated from bounding boxes that do not, using the following rules:

- In a dataset that does not cross the 180 degree meridian, the westernmost longitude shall always be less than the easternmost longitude;
- Conversely, if a bounding box crosses the 180 degree meridian, the westernmost longitude shall be greater than the easternmost longitude.

Other constraints on geographical bounding boxes:

- Geographical points shall be designated with the northernmost and southernmost latitudes equal, and with the westernmost and easternmost longitudes equal;
- Except for a geographical point, the total longitudinal span shall be greater than zero and less than or equal to 360 degrees;
- The northernmost latitude shall always be greater than or equal to the southernmost latitude;
- Longitude and latitude shall be recorded in a coordinate reference system that has the same axes, units and prime meridian as WGS84.

==== Geographic identifier

.Geographic identifier
[cols="1,1"]
|===

|Necessity
|Optional

|Template value
a|
(ADD GEOGRAPHIC IDENTIFIER INFORMATION*O) +
ADD GEOGRAPHIC IDENTIFIER THESAURUS NAME*O +
ADD GEOGRAPHIC IDENTIFIER CODE*C MW

|Information
|Geographic identifier indicating the zone covered on earth by the product

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:extent/*/gmd:geographicElement/\*/gmd:geographicIdentifier/gmd:MD_Identifier/code/*/text()`

|===

The optional geographic identifier indicates the area covered by the product. It can be used when the identifier is a well-known name (within a targeted user community), a codified acronym for an area (such as a region), or a feature (such as a water storage or coastline section). If the geographicIdentifier block is used, a code must be provided.

The `geographicIdentifier` can be expressed in two ways:

- With just the `geographicIdentifier` code and a link to the related codelist (authority):
```xml
<gmd:extent>
   <gmd:EX_Extent id="geographicExtent">
      <gmd:geographicElement>
	 <gmd:EX_GeographicDescription id="SouthAustralia__allGensRegister">
	    <gmd:geographicIdentifier>
	       <gmd:MD_Identifier>                        
		  <gmd:code>
		     <gco:CharacterString>
			   South Australia (SA)
			    (http://find.ga.gov.au/FIND/profileinfo/anzlic-allgens.xml#SA)
		     </gco:CharacterString>
		  </gmd:code>
	       </gmd:MD_Identifier>
	    </gmd:geographicIdentifier>
	 </gmd:EX_GeographicDescription>
      </gmd:geographicElement>
   </gmd:EX_Extent>
</gmd:extent>
```
- With the `geographicIdentifier` code, as well as a link to the related codelist, using a `CI_Citation` group:
```xml
<gmd:extent>
   <gmd:EX_Extent id="geographicExtent">
     <gmd:geographicElement>
       <gmd:EX_GeographicDescription id="SouthAustralia__allGensRegister">
	  <gmd:geographicIdentifier>
	     <gmd:MD_Identifier>
		<gmd:authority>
		   <gmd:CI_Citation>
		      <gmd:title>
			 <gco:CharacterString>
			 ANZLIC Geographic Extent Name Register
			 (http://find.ga.gov.au/FIND/profileinfo/anzlic-allgens.xml) 
			 </gco:CharacterString>
		      </gmd:title>
		      <gmd:alternateTitle>
			 <gco:CharacterString>
			 ANZLIC AllGens / subcategory: anzlic-sla_2001edition 
			 </gco:CharacterString>
		      </gmd:alternateTitle>
		      <gmd:date>
			 <gmd:CI_Date>
			    <gmd:date>
			       <gco:Date>2011-10-25</gco:Date>
			    </gmd:date>
			    <gmd:dateType>
			       <gmd:CI_DateTypeCode 
codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
			    </gmd:dateType>
			 </gmd:CI_Date>
		      </gmd:date>
		   </gmd:CI_Citation>
		</gmd:authority>
		<gmd:code>
		   <gco:CharacterString>South Australia (SA) 
			  (http://find.ga.gov.au/FIND/profileinfo/anzlic-allgens.xml#SA) 
		   </gco:CharacterString>
		</gmd:code>
	     </gmd:MD_Identifier>
	  </gmd:geographicIdentifier>
       </gmd:EX_GeographicDescription>
    </gmd:geographicElement>
  </gmd:EX_Extent>
</gmd:extent>
```

===== Station identifiers for GTS bulletins

In WIS metadata records, references to stations for a GTS bulletin should point to WIGOS station identifiers (available through the Observing Systems Capability Analysis and Review tool (OSCAR)/Surface) and should be provided as keywords (see section 5.8.1.8.3).

==== Descriptive keywords

Descriptive keywords are additional “controlled” terms which further classify (thus increasing searching accuracy for) the products. The following general rules apply for keywords in a WCMP record:

. Terms from the same keyword thesaurus/codelist and of the same `KeywordTypeCode` shall be grouped into a single instance of the `<gmd:descriptiveKeywords>` class;
. All WCMP metadata records shall have at least one `WMO_CategoryCode` keyword, and the related `KeywordTypeCode` will be `"theme"`;
. All WCMP records for GTS data must contain a keyword from the `WMO_DistributionScopeCode` codelist and must be accompanied by the `KeywordTypeCode = "dataCentre"`;
. A WCMP metadata record describing data for global exchange via the WIS shall indicate the scope of distribution using the keyword `"GlobalExchange"` of type `"dataCentre"`;
. Where data concern WMO stations, the related WIGOS station identifiers should be recorded as keywords (see 5.8.1.8.3);
. Any data parameter term added as a keyword should be accompanied by the `KeywordTypeCode = "dataParam"`.

===== WMO_CategoryCode keyword

.WMO_CategoryCode keyword
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
|ADD-WCMP-WMO-CATEGORY-CODE*M

|Information
|One or more `WMO_CategoryCode` keywords for classifying the product

|Category
|Product information

|XPath
a|
* `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:keyword/*/text()`
* `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:type/*/@codeListValue="theme"`
* `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:thesaurusName/\*/gmd:title/*/text()="WMO_CategoryCode"`

|===

Any WCMP metadata record shall have at least one `WMO_CategoryCode` keyword, and the related `KeywordTypeCode` will be `"theme"`.

The `WMO_CategoryCode` list of terms is occasionally revised. For the latest list of terms, see: http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode.

At the time of writing, the `WMO_CategoryCode` list of terms includes: 

.WMO_CategoryCode list of terms
[cols="1,1"]
|===
|WMO_CategoryCode | Term

|WMO_CategoryCode_weatherObservations
|weatherObservations

|WMO_CategoryCode_weatherForecasts
|weatherForecasts

|WMO_CategoryCode_meteorology
|Meteorology

|WMO_CategoryCode_hydrology
|Hydrology

|WMO_CategoryCode_climatology
|Climatology

|WMO_CategoryCode_landMeteorologyClimate
|landMeteorologyClimate

|WMO_CategoryCode_synopticMeteorology
|synopticMeteorology

|WMO_CategoryCode_marineMeteorology
|marineMeteorology

|WMO_CategoryCode_agriculturalMeteorology
|agriculturalMeteorology

|WMO_CategoryCode_aerology
|Aerology

|WMO_CategoryCode_marineAerology
|marineAerology

|WMO_CategoryCode_oceanography
|Oceanography

|WMO_CategoryCode_landHydrology
|landHydrology

|WMO_CategoryCode_rocketSounding
|rocketSounding

|WMO_CategoryCode_pollution
|Pollution

|WMO_CategoryCode_waterPollution
|waterPollution

|WMO_CategoryCode_landWaterPollution
|landWaterPollution

|WMO_CategoryCode_seaPollution
|seaPollution

|WMO_CategoryCode_landPollution
|landPollution

|WMO_CategoryCode_airPollution
|airPollution

|WMO_CategoryCode_glaciology
|Glaciology

|WMO_CategoryCode_actinometry
|Actinometry

|WMO_CategoryCode_satelliteObservation
|satelliteObservation

|WMO_CategoryCode_airplaneObservation
|airplaneObservation

|WMO_CategoryCode_observationPlatform
|observationPlatform

|WMO_CategoryCode_spaceWeather
|spaceWeather

|WMO_CategoryCode_atmosphericComposition
|atmosphericComposition

|WMO_CategoryCode_radiation
|radiation

|===

The example below, for a satellite product, uses the terms `"satelliteObservation"` and `"meteorology"` as keywords from the `WMO_CategoryCode` thesaurus/codelist:

====== Example: Descriptive keywords / WMO_CategoryCode keyword
```xml
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>satelliteObservation</gco:CharacterString>
    </gmd:keyword>
    <gmd:keyword>
      <gco:CharacterString>meteorology</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
    <MD_KeywordTypeCode xmlns="http://www.isotc211.org/2005/gmd" codeListValue="theme" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode">Theme</MD_KeywordTypeCode>
    </gmd:type>
    <gmd:thesaurusName>
    <gmd:CI_Citation>
          <gmd:title>
            <gco:CharacterString>WMO_CategoryCode</gco:CharacterString>
          </gmd:title>
          <gmd:date>
            <gmd:CI_Date>
               <gmd:date>
                  <gco:Date>2016-04-01</gco:Date>
               </gmd:date>
                <gmd:dateType>
                  <gmd:CI_DateTypeCode codeListValue="publication" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode"/>
               </gmd:dateType>
           </gmd:CI_Date>
          </gmd:date>
        </gmd:CI_Citation>
    </gmd:thesaurusName>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

===== WMO_DistributionScopeCode keywords 

.WMO_DistributionScopeCode keywords
[cols="1,1"]
|===

|Necessity
|Conditional. Mandatory for WCMP 1.3 for GTS data

|Template value
|ADD-DISTRIBUTION-SCOPE*C

|Information
|Scope of distribution of data within the WIS

|Category
|Product information

|XPath
a|
* `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:keyword/*/text()`
* `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:type/*/@codeListValue="dataCentre"`
* `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:thesaurusName/\*/gmd:title/*/text()="WMO_DistributionScopeCode"`

|===

Any WCMP record for GTS data must contain a `WMO_DistributionScopeCode` keyword. The scope of distribution for data within WIS shall be expressed with a term from the `WMO_DistributionScopeCode` vocabulary, using the `KeywordTypeCode = "datacentre"`. The keyword will be one of the following terms from the `WMO_DistributionScopeCode` vocabulary (a metadata record may not contain more than one of these keywords):

. GlobalExchange
. RegionalExchange
. OriginatingCentre

The requirements for a WIS Discovery Metadata record describing products for global exchange via the WIS are more stringent. Such a record shall contain, in the `resourceConstraints` section, the keyword `"GlobalExchange"` from the `WMO_DistributionScopeCode` thesaurus (codelist), with `KeywordTypeCode = "dataCentre"`; it must also include a term from both the `WMO_DataLicenseCode` and `WMO_GTSProductCategoryCode` thesauri (see section 5.8.1.10 for details).

The GTS is the part of the WIS concerned with rapid, near-real-time information exchange. The GISCs are required to retain at least 24h of information exchanged globally using the GTS.

A keyword from the `WMO_DistributionScopeCode` codelist is used to indicate whether the product described by a metadata record is or is not delivered via the GTS and GISCs, and, within the GTS, whether it is exchanged globally or regionally:

. Metadata marked `"GlobalExchange"` or `"RegionalExchange"` describe product delivered via the GTS. Products are transmitted from an originating NC or DCPC to the principal GISC, distributed to all (or some) GISCs, then placed on the GISC caches;
. Metadata marked `"RegionalExchange"` describe products that, while transmitted on the GTS, might be simply exchanged between two WMO Members (by bilateral agreement). Some examples are regional warnings or voluminous NWP products;
. The metadata marked `"OriginatingCentre"` indicate non-GTS products and include, for instance, products delivered to users from a DCPC.

Below is an example for globally exchanged GTS products:

====== Example: Descriptive keywords / WMO_DistributionScopeCode keywords 
```xml
<gmd:descriptiveKeywords>
    <gmd:MD_Keywords>
        <gmd:keyword>
            <gco:CharacterString>GlobalExchange</gco:CharacterString>
        </gmd:keyword>
        <gmd:type>
            <gmd:MD_KeywordTypeCode codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_KeywordTypeCode" codeListValue="dataCentre">dataCentre</gmd:MD_KeywordTypeCode>
        </gmd:type>
        <gmd:thesaurusName>
            <gmd:CI_Citation>
                <gmd:title>
                    <gco:CharacterString>WMO_DistributionScopeCode [http://wis.wmo.int/2012/codelists/WMOCodeLists.xml]</gco:CharacterString>
                </gmd:title>
                <gmd:date>
                    <gmd:CI_Date>
                        <gmd:date>
                            <gco:Date>2012-06-27</gco:Date>
                        </gmd:date>
                        <gmd:dateType>
                            <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
                        </gmd:dateType>
                    </gmd:CI_Date>
                </gmd:date>
            </gmd:CI_Citation>
        </gmd:thesaurusName>
    </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

===== WIGOS Station Identifier keywords

.WIGOS Station Identifier keywords
[cols="1,1"]
|===

|Necessity
|Optional for WCMP 1.3

|Template value
a|
ADD WIGOS STATION IDENTIFIER CODE*O +
ADD WIGOS STN ID CODE AUTHORITY*O

|Information
|Where a product includes data from stations that have been assigned a WIGOS station identifier, include this as a keyword

|Category
|Product information

|XPath
a|
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:keyword/*/text()`
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:type/*/@codeListValue="place"`
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:thesaurusName/\*/ gmd:title/*/text()="WMO WIGOS Station Identifiers"`

|===

Whereas metadata records previously included WMO station numbers as keywords, the WIGOS Station Identifier should now be used. The related `KeywordTypeCode` should be `"place"`.

====== Example: Descriptive keywords / WIGOS Station Identifier keywords
```xml
<gmd:descriptiveKeywords>
   <gmd:MD_Keywords>
       <gmd:keyword> 
         <gco:CharacterString>
          0-20000-0-94287; CAIRNS AERO [http://data.wmo.int/wigosid=0-20000-0-94287]
         </gco:CharacterString>
       </gmd:keyword>
       <gmd:keyword> 
         <gco:CharacterString>
          0-20000-0-94374; ROCKHAMPTON AERO [http://data.wmo.int/wigosid=0-20000-0-94374]
         </gco:CharacterString>
       </gmd:keyword>
       <gmd:keyword>
         <gco:CharacterString>
          0-20000-0-94294; TOWNSVILLE AERO [http://data.wmo.int/wigosid=0-20000-0-94294]
         </gco:CharacterString>
       </gmd:keyword>
       <gmd:type>
          <gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_KeywordTypeCode"  codeListValue="place"</gmd:MD_KeywordTypeCode>
       </gmd:type> 
       <gmd:thesaurusName>
          <gmd:CI_Citation>
             <gmd:title>
                  <gco:CharacterString>WMO WIGOS Station Identifiers</gco:CharacterString>
             </gmd:title>
              <gmd:date>
                 <gmd:CI_Date>
                    <gmd:date>
                       <gco:Date>2016-06-25</gco:Date>
                    </gmd:date>
                 <gmd:dateType>
                     <gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
                 </gmd:dateType>
              </gmd:CI_Date>
           </gmd:date>
       </gmd:CI_Citation>
    </gmd:thesaurusName>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

===== Data parameters 

.Data parameters
[cols="1,1"]
|===

|Necessity
|Optional for WCMP 1.3

|Template value
|ADD-DATA-PARAMETER*O

|Information
|Data parameter keywords for classifying the product

|Category
|Product information

|XPath
a|
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:keyword/*/text()`
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:descriptiveKeywords/*/gmd:type/*/@codeListValue="dataParam"`
|===

Where feasible, a list of the data parameters may be added as keywords. These should be added under a separate `"descriptiveKeywords"` block and should use the `KeywordTypeCode = "dataParam"`.

======= Example: Descriptive keywords / Data parameters
```xml
<gmd:descriptiveKeywords>
   <gmd:MD_Keywords>
      <gmd:keyword>  
         <gco:CharacterString>Dewpoint temperature</gco:CharacterString>
      </gmd:keyword> 
       <gmd:type> 
          <gmd:MD_KeywordTypeCode codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists#MD_KeywordTypeCode" codeListValue="dataParam">dataParam</ gmd:MD_KeywordTypeCode>
       </gmd:type>
       <gmd:thesaurusName>
          <gmd:CI_Citation>
             <gmd:title>
                <gco:CharacterString>WMO Grib2 parameter list http://codes.wmo.int/grib2/codeflag/4.2/ </gco:CharacterString>
             </gmd:title> 
              <gmd:date>
                 <gmd:CI_Date>
                    <gmd:date>
                       <gco:Date>2016-06-25</gco:Date>
                    </gmd:date>
                 <gmd:dateType>
                    <gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
                 </gmd:dateType>
              </gmd:CI_Date>
           </gmd:date>
       </gmd:CI_Citation> 
    </gmd:thesaurusName>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

==== Product sample visualization URL

.Product sample visualization URL
[cols="1,1"]
|===

|Necessity
|Optional for WCMP 1.3, but used by WIS portal to display products

|Template value
|ADD-PRODUCT-IMAGERY-URL*O

|Information
|URL to a sample data visualization

|Category
|Product information

|XPath
a| `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:graphicOverview/*/gmd:fileName/*/text()`

|===

The addition of a link to the product visualization is suggested, when possible. The display of related linked images can make the product more attractive for end users.

Below is an example based on EUMETSAT Seviri Level 1.5: 

====== Example: Product sample visualization URL
```xml
<gmd:graphicOverview>
   <gmd:MD_BrowseGraphic>
      <gmd:fileName>
         <gco:CharacterString>http://navigator.eumetsat.int:80/smartEditor/preview/msg-level-1-5.jpg</gco:CharacterString>
      </gmd:fileName>
      <gmd:fileDescription>
         <gco:CharacterString>preview</gco:CharacterString>
      </gmd:fileDescription>
      <gmd:fileType>
         <gco:CharacterString>jpg</gco:CharacterString>
      </gmd:fileType>
   </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

==== Data policy information

.Data policy information
[cols="1,1"]
|===

|Necessity
a|Mandatory for WCMP 1.3, for data intended for global exchange on the GTS. 
  Otherwise, highly recommended, since the absence of a policy can result in users assuming that there are no limitations on data use.
  To avoid uncertainty, where there are no limitations, use the data policy `"NoLimitation"`.

|Template value
|ADD-DATA-POLICY-CODE*C

|Information
|Data usage and access limitations

|Category
|Product information

|XPath
a|
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:resourceConstraints/gmd:MD_LegalConstraints//gmd:otherConstraints/*/text()=WMO_DataLicenseCode`
. `/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:resourceConstraints/gmd:MD_LegalConstraints//gmd:otherConstraints/*/text()=WMO_GTSProductCategoryCode`

|===

The data policy category is used to specify the conditions under which the data products can be accessed and used. Completing the data policy section of a WCMP metadata record is dependent on the type of product, the data policy and the ways in which the product is being distributed. For those reasons, and to minimize the complexity of this section, three representative examples are discussed: 

. Non-GTS product, with a policy of no constraints on use or distribution;
. Non-GTS product, with a policy applicable in the WMO context;
. GTS product intended for global exchange.

For more comprehensive information, please refer to the documentation on WCMP contained in the Manual on WIS. 

When adding the data policy information, two different parts of the metadata record have to be filled: 

- `resourceConstraints`, which contains the data policy information; 
- Scope of distribution, using one of the following terms: `"GlobalExchange"`, `"RegionalExchange"` or `"OriginatingCentre"` (to be inserted as a keyword, as explained in Section 5.8.1.8.2). 

Each of the three examples below shows the `resourceConstraints` part of the information that is to be added to the metadata record. 

Within the `resourceConstraints` section, a term from the `DataLicenseCode` codelist is added into an `otherConstraints` field and an explanation of the data policy is typically given in an additional `otherConstraints` field:

```xml
/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints/*/text()
```

Allowable terms from the `DataLicenseCode` codelist include: `"WMOAdditional"`, `"WMOEssential"`, `"WMOOther"` or `"NoLimitation"`. All of these terms are defined at http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode.

===== Example 1: Non-GTS product with a policy of no constraints on use or distribution

Publicly available datasets are those for which there are no limitations on distribution or use.

The `useLimitation` field in the `resourceConstraints` block should contain `"No conditions apply"`, and an `otherConstraints` field should contain the phrase `"NoLimitation"`.

```xml
<!-- Example of publicly available, unrestricted data -->
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <!--  add useLimitation with ..No conditions apply..  -->
    <gmd:useLimitation>
      <gco:CharacterString>No conditions apply</gco:CharacterString>
    </gmd:useLimitation>
    <gmd:useConstraints>
      <!--  Restriction code have to point to WMOCodeLists.xml -->
<gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode"
         codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
    </gmd:useConstraints>
    <!--  otherConstraints with ..NoLimitation..  -->
    <gmd:otherConstraints>
      <gco:CharacterString>NoLimitation</gco:CharacterString>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

In addition, the scope of distribution should ideally be stated as a keyword, and for non-GTS products it should be `"OriginatingCentre"`.

```xml
<!-- Scope of distribution for non GTS products: OriginatingCentre -->
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <!--  keyword OriginatingCentre applies for DCPC Data -->
      <gco:CharacterString>OriginatingCentre</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_DistributionScopeCode"
           codeListValue="dataCentre">dataCentre</gmd:MD_KeywordTypeCode>
    </gmd:type>
    <gmd:thesaurusName>
      <gmd:CI_Citation>
        <gmd:title>
          <gco:CharacterString>WMO_DistributionScopeCode, WMOCodelists dictionary Version 1.3 [http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DistributionScopeCode]</gco:CharacterString>
        </gmd:title>
    .. .. .. etc    (see Section 5.8.1.8.2 for full details)
```

===== Example 2: Non-GTS product with a policy applicable in the WMO context

This example describes a product that is not distributed on the GTS and has a single data policy applicable in the WMO context. Note that policies that are applicable in the WMO context, and therefore flagged in an `otherConstraints` field with the term `"WMOOther"`, will be presented by the GISCs to users when they discover the data. GISCs have no obligation to show the other data policies.

A term from the `WMO_DataLicenseCode` codelist (available at http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode) should be added to an `otherConstraints` field.

Note:	The data policy term `"WMOOther"` can also be used for data that is delivered via the GTS.

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <!--   Add useLimitation to indicate the limitations of usage for the data  -->
      <gmd:useLimitation>
        <gco:CharacterString>Disclaimer - While every effort has been made to ensure that these data are accurate and reliable within the limits of the current state of the art, OrganisationX cannot assume liability for any damages caused by any errors or omissions in the data, nor as a result of the failure of the data to function on a particular system. OrganisationX makes no warranty, expressed or implied, nor does the fact of distribution constitute such a warranty.
        </gco:CharacterString>
      </gmd:useLimitation>      
      <gmd:accessConstraints>
<gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="copyright">copyright</gmd:MD_RestrictionCode>
      </gmd:accessConstraints>
      <gmd:accessConstraints>
         <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
      </gmd:accessConstraints>
      <gmd:useConstraints>
        <gmd:MD_RestrictionCode 
codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="copyright">copyright</gmd:MD_RestrictionCode>
      </gmd:useConstraints>
      <gmd:useConstraints>
         <gmd:MD_RestrictionCode 
codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
      </gmd:useConstraints>
      <!--  Add WMOOther, to signal that the policy is applicable in the WMO Context -->
      <gmd:otherConstraints>
         <gco:CharacterString>WMOOther
Ordnance Survey Open Data License [https://www.ordnancesurvey.co.uk/docs/licences/os-opendata-licence.pdf]
         </gco:CharacterString>
      </gmd:otherConstraints>    
   </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

The scope of distribution should, ideally, be added as a keyword using the term `"OriginatingCentre"`.

Please refer to the encoding of scope of distribution, provided under Example 1 above or in section 5.8.1.8.2.

===== Example 3: GTS data intended for global exchange

This example describes data distributed via the GTS and available from the cache at a GISC. For data delivered via the GTS, the data policy term to be added to the `otherConstraints` field can only be `"WMOAdditional"` or `"WMOEssential"` – both of these terms are defined at http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode.

In the example below, the code used is `"WMOEssential"`.

WMO policies for data and products (licence conditions) are defined by Resolution 40 (Cg-XII), Resolution 25 (Cg-XIII) and Resolution 60 (Cg-17). Data and products exchanged on a free and unrestricted basis are marked as `"WMOEssential"`; data classed as `"WMOAdditional"` have restrictions on commercial activities. Operational meteorological information for aviation is not included in these resolutions but is controlled by the International Civil Aviation Organization (ICAO); this information is an example of `"WMOOther"` data. 

Only one term from the `WMO_DataLicenseCode` codelist may be used within a metadata record. As well as assigning one of these terms, it is expected, where the term used is `"WMOOther"` or `"WMOAdditional"`, that further clarification of the licence constraints will also be provided (either directly in the metadata record or else via a URL).

For data circulating on the GTS, `"WMOAdditional"` is used to qualify products under the WMOAdditional data policy; `"WMOEssential"` is used for products made available under the WMO Essential data policy; and “WMOOther” can be used (where applicable) for other products, regardless of whether the data is being delivered via the GTS, GISC or otherwise.

Where data is for global exchange on the GTS (which is signified by the `WMO_DistributionScopeCode` keyword), both a `WMO_DataLicenseCode` and a `WMO_GTSProductCategoryCode` term must be provided, under `resourceConstraints`. The terms from the `WMO_GTSProductCategoryCode` codelist to be used are: `"GTSPriority1"`, `"GTSPriority2"`, `"GTSPriority3"` and `"GTSPriority4"`.

Below is the `resourceConstraints` element for a `"WMOEssential"` GTS product intended for global exchange:

```xml
<!--   Data intended for WMOEssential data intended for Global exchange -->
<gmd:resourceConstraints>
   <gmd:MD_LegalConstraints>
      <gmd:useLimitation>
        <gco:CharacterString>Data is near realtime, and is not quality controlled. License conditions apply, as indicated below</gco:CharacterString>
      </gmd:useLimitation>
      <!--   MD_RestrictionCode to be "otherRestrictions" -->
      <gmd:accessConstraints>
<gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="copyright">copyright</gmd:MD_RestrictionCode>
      </gmd:accessConstraints>
      <gmd:accessConstraints>
         <gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
      </gmd:accessConstraints>
      <gmd:useConstraints>
        <gmd:MD_RestrictionCode 
codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="copyright">copyright</gmd:MD_RestrictionCode>
      </gmd:useConstraints>
      <gmd:useConstraints>
         <gmd:MD_RestrictionCode 
codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
      </gmd:useConstraints>
      <!-- Add WMO Data policy and GTSPriority -->
      <gmd:otherConstraints>
         <gco:CharacterString>WMOEssential A definition of "WMOEssential" is available at: http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode </gco:CharacterString>
      </gmd:otherConstraints>
      <gmd:otherConstraints>
         <gco:CharacterString>GTSPriority2</gco:CharacterString>
      </gmd:otherConstraints>
   </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

In addition, the scope of distribution of data marked as `"GlobalExchange"` has to be added as a keyword (with `KeywordTypeCode = "dataCentre"`).

```xml
<!-- keyword for stating the scope of distribution: Global Exchange   -->
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>GlobalExchange</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_DistributionScopeCode"
           codeListValue="dataCentre">dataCentre</gmd:MD_KeywordTypeCode>
    </gmd:type>
  .. .. .. etc   (see section 5.8.1.8.2 for full example)
```

==== Distribution information

.Distribution information
[cols="1,1"]
|===

|Necessity
|Highly recommended for WCMP 1.3

|Template value
a|
ADD URL TO DATA ACCESS SERVICE*HR MW +
ADD DISTRIBUTOR SHORTNAME*HR +
ADD DISTRIBUTOR EMAIL ADDRESS*HR +
ADD FORMAT NAME*O MW +
ADD FORMAT VERSION*O MW

|Information
|Resource format, distributor information (as short, e.g.:EUM) and resource transfer options (URLs)

|Category
|Product information

|XPath
a|
. `/gmd:MD_Metadata/gmd:distributionInfo/\*/gmd:distributionFormat/*/gmd:formatDistributor/*/distributorContact/gmd:CI_ResponsibleParty`
. `/gmd:MD_Metadata/gmd:distributionInfo/\*/gmd:distributionFormat/*/gmd:formatDistributor/*/distributorTransferOptions/*/gmd:online/`

|===

Below is an example of a GRIB product made available via an FTP server (for readability, distributor details are not included in this snippet):

====== Example: Distribution information
```xml
<gmd:distributionInfo>
    <gmd:MD_Distribution>
        <gmd:distributionFormat>
            <gmd:MD_Format>
                <gmd:name>
                    <gco:CharacterString>GRIB</gco:CharacterString>
                </gmd:name>
                <gmd:version>
                    <gco:CharacterString>FM 92 GRIB Edition 2</gco:CharacterString>
                </gmd:version>
                <gmd:specification>
                    <gco:CharacterString>http://www.wmo.int/pages/prog/www/WMOCodes.html</gco:CharacterString>
                </gmd:specification>
            </gmd:MD_Format>
        </gmd:distributionFormat>
        <gmd:transferOptions>
            <gmd:MD_DigitalTransferOptions>
                <gmd:onLine>
                    <gmd:CI_OnlineResource>
                        <gmd:linkage>
                            <gmd:URL>ftp://data-portal.ecmwf.int/</gmd:URL>
                        </gmd:linkage>
                        <gmd:protocol>
                            <gco:CharacterString>WWW:DOWNLOAD-1.0-ftp--download</gco:CharacterString>
                        </gmd:protocol>
                        <gmd:name>
                            <gco:CharacterString>ECMWF DCPC FTP Server</gco:CharacterString>
                        </gmd:name>
                        <gmd:description>
                            <gco:CharacterString>WMO Information System download service through ECMWF DCPC</gco:CharacterString>
                        </gmd:description>
                        <gmd:function>
                            <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="download">download</gmd:CI_OnLineFunctionCode>
                        </gmd:function>
                    </gmd:CI_OnlineResource>
                </gmd:onLine>
            </gmd:MD_DigitalTransferOptions>
        </gmd:transferOptions>
    </gmd:MD_Distribution>
</gmd:distributionInfo>
```

==== Party to be recognized as the originator of the information

.Party to be recognized as the originator of the information
[cols="1,1"]
|===

|Necessity
|Optional for WCMP 1.3

|Template value
|ADD-CITED-RESPONSIBLE-PARTY-ORGANISATION*O-MW

|Information
|Party that should be cited as the originator (that is, data author) of the resource.

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:distributionInfo/\*/gmd:distributionFormat/*/gmd:formatDistributor/*/distributorContact/gmd:CI_ResponsibleParty` (complex content)

|===

When the data owners wish to be cited in references to their data, they can stipulate this in the `citedResponsibleParty` block, using the role `"originator"`.

Below is an example:

====== Example: Party to be recognized as the originator of the information
```xml
<gmd:identificationInfo>
<gmd:MD_DataIdentification>
   <gmd:citation>
      <gmd:CI_Citation>
         …. .. .. ..
         <gmd:citedResponsibleParty>
            <gmd:CI_ResponsibleParty>
                <gmd:organisationName>
                    <gco:CharacterString>EUMETSAT</gco:CharacterString>
                </gmd:organisationName>
                <gmd:role>
                    <gmd:CI_RoleCode     codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_ScopeCode" codeListValue="pointOfContact">originator</gmd:CI_RoleCode>
                </gmd:role>
            </gmd:CI_ResponsibleParty>
         </gmd:citedResponsibleParty>
         <gmd:otherCitationDetails>
             <gco:CharacterString>Add other citing instructions here</gco:CharacterString>
         </gmd:otherCitationDetails>
           .. .. .. .. 
       </gmd:CI_Citation>
    </gmd:citation>
     .. .. .. ..
  </gmd:MD_DataIdentification>
</gmd:identificationInfo>
```

Further details on how the item should be cited can be added to the `otherCitationDetails` block.

==== Frequency of resource updates 

.Frequency of resource updates
[cols="1,1"]
|===

|Necessity
|Optional for WCMP 1.3

|Template value
a|ADD PRODUCT UPDATE FREQ PERIOD*O +
ADD PRODUCT UPDATE FREQ CODE*O MW

|Information
|Frequency of resource update

|Category
|Product information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/\*/gmd:resourceMaintenance/*/gmd:maintenanceAndUpdateFrequency/`

|===

If the block on resource maintenance and update frequency is used, the `MD_MaintenanceFrequencyCode` is mandatory.

The example below shows a product  that is available every 6 hours starting at 03 UTC.

====== Example: Frequency of resource updates 
```xml
<gmd:resourceMaintenance>
   <gmd:MD_MaintenanceInformation>
      <gmd:maintenanceAndUpdateFrequency>
         <gmd:MD_MaintenanceFrequencyCode codeListValue="irregular" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_MaintenanceFrequencyCode"/>
      </gmd:maintenanceAndUpdateFrequency>
      <gmd:userDefinedMaintenanceFrequency>
         <gts:TM_PeriodDuration>PT6H</gts:TM_PeriodDuration>
      </gmd:userDefinedMaintenanceFrequency>
      <gmd:maintenanceNote>
         <gco:CharacterString>ADD-PRODUCT-UPDATE-FREQ-NOTE (e.g. Instances of bulletin SIKB20NGTT are available every 6 hours starting at 03 UTC)</gco:CharacterString>
      </gmd:maintenanceNote>
   </gmd:MD_MaintenanceInformation>
</gmd:resourceMaintenance>
```

=== Mandatory WIS technical information

In addition to the mandatory elements included in section 5.8.1 above, the following information is required:

==== Metadata record unique identifier

.Metadata record unique identifier
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
|ADD-WCMP-IDENTIFIER*M

|Information
|Unique identifier (UID) for individual WIS discovery metadata records

|Category
|WIS technical information

|XPath
a|`/gmd:MD_Metadata/gmd:fileIdentifier/*/text()`

|===

The WCMP UID (`fileIdentifier`) has to be globally unique, that is, no two WIS metadata records can have the same WCMP UID.

In the absence of any system, defined by the organization creating a metadata record, that ensures uniqueness of the WCMP UID, this should be structured as follows:

	urn:x-wmo:md:DataProviderInternetDomainName::ProductUID

where:

* `:` is used as a separator;
* `urn:x-wmo:md:` is mandatory;
* `DataProviderInternetDomainName::` designates the citation authority, based on the reversed Internet domain name of the data provider (for example, int.eumetsat, gov.noaa); please note the recommended use of two colons `::`. For products exchanged on the GTS, the required form is `int.wmo.wis::`.
* `ProductUID` is a unique identifier whose structure is defined by the organization responsible for the metadata record.

Examples:

* UID for northern hemisphere satellite cloud information chart from Japan: `urn:x-wmo:md:jp.go.jma.wis.dcpc-sat::WAID`
* UID for an outgoing long-wave radiation product from the FY-2D satellite: `urn:x-wmo:md:cn.gov.cma::NSMC.FY2D.OLR_MLT_OTG.BAWX``

===== Unique identifier for GTS products

Additional rules apply to metadata records describing products distributed through the GTS. The file identifier for bulletin metadata has the following structure:

	urn:x-wmo:md:int.wmo.wis::{uid}

where `{uid}` is a unique identifier derived from the GTS bulletin or file name.

Further background information on constructing a file identifier for products distributed through the GTS is available in the WMO Core Metadata Profile version 1.3, Part 1, section 9.2.

An example of file identifier for a Deutscher Wetterdienst Numerical Weather Prediction Model is:

	urn:x-wmo:md:int.wmo.wis::HTXC85EDZW

An example of file identifier for Meteo France Numerical Weather Prediction Model is:

	urn:x-wmo:md:int.wmo.wis::FR-meteofrance-toulouse,GRIB,ARPEGE-75N10N-60W65E_C_LFPW

==== Metadata modification - DateStamp

.Metadata modification - DateStamp
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
|ADD-METADATA-LAST-MODIFICATION-DATE*M

|Information
|Date when the metadata record was last modified

|Category
|WIS technical information

|XPath
a|`/gmd:MD_Metadata/gmd:dateStamp`

|===

This shows when the metadata record was last modified and has the following date pattern: `YYYY-MM-DDThh:mm:ss`, for example `2015-12-29T11:45:55`.

==== Product creation date

.Product creation date
[cols="1,1"]
|===

|Necessity
|Mandatory for WCMP 1.3

|Template value
|ADD-PRODUCT-CREATION-DATE*M

|Information
|Creation date of the product

|Category
|WIS technical information

|XPath
a|`/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:citation/*/gmd:date/*//gmd:date/*/text()`
a|`/gmd:MD_Metadata/gmd:identificationInfo/*/gmd:citation/*/gmd:date/*/gmd:dateType/*/@codeListValue="creation"`

|===

This shows when the product was created and has the following date pattern: `YYYY-MM-DD` or `YYYY-MM-DDThh:mm:ss`. See also section 5.8.1.5 for details of the date/time format.

====== Example: Product creation date
```xml
<gmd:date>
   <gmd:CI_Date>
      <gmd:date>
         <gco:Date>2015-03-23</gco:Date>
      </gmd:date>
      <gmd:dateType>
         <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation"/>
      </gmd:dateType>
   </gmd:CI_Date>
<gmd:date>
```

