== Annex. Criteria for Creating a Metadata Record That Represents a Collection of Products

This annex defines criteria and other elements to consider when creating a metadata record that represents a collection of products.

To understand the notion of collection, it is important to distinguish between a dataset and a temporal subset of a dataset. Meteorological data is often transient (for example, observations, forecasts and NWP products) and continuously updated. A dataset is typically seen as an aggregate of temporal instances or subsets (the collection) and, as explained below, metadata for a dataset is not typically set at the instance level. This is so even when a new instance or subset of a dataset is produced daily, and when only the latest day of data is ever available (in that case, the `temporalExtent` of the dataset is “latest 24 hours only”).

The criteria to be considered when creating the collection metadata record include:

==== Size of dataset instances:

An important consideration, in terms of dataset granularity, is how the dataset instances will be made available to end users; for instance, push or pull services, with filter capabilities or not.

Numerical model output could be seen as a four- and even five-dimensional dataset (latitude, longitude, height, time, reference time). It is possible to set granularity at this level, but the amount of data would be huge, and it would not be possible to exchange the whole dataset using “push” mode. Such large scale granularity of data is ideally provided via download (or publish-subscribe) services with subsetting capabilities (for instance, Web Coverage Service (WCS) or direct download INSPIRE services).
  When the data provider is not able to implement such services, and when only predefined datasets or time windows are made available (for example, datasets for global exchange on the WIS) the granularity may have to be finer. For example, the French high-resolution model, AROME, is split into two daily subsets:

** Dataset 1: AROME 0°01 FRANCE − 00h−23h
** Dataset 2: AROME 0°01 FRANCE − 24h−45h

where Dataset 1 covers hourly steps H to H+23h and Dataset 2 covers hourly steps H+24 to H+45.

The granularity of the subsets is chosen according to the size of the instances to be exchanged, and the size of the granules (500 Mb, 1Gb, etc.) should be compatible with the bandwidth available for data exchange. 
Note that it is also possible to define an aggregate of two subsets, for instance:
** Dataset 0: AROME 0°01 FRANCE

where Dataset 0 is an aggregate of Dataset 1 and Dataset 2;

==== Content consistency:

It is recommended, if possible, not to blend multiple data categories or topics in the same dataset, which would result in a heterogeneous aggregate. For example, an aggregate of satellite observations and weather forecasts would typically not make sense (unless they had been combined for a particular purpose); whereas an aggregate of lake pollution and river pollution data makes sense, especially if the data processing has been similar and the data license is the same.

More generally, dataset heterogeneity in terms of content can result in very vague descriptions in the metadata, which will in turn affect data discoverability on the WIS;

==== Update frequency and other temporal characteristics:

The refresh rate of data also has to be taken into account, in terms of dataset granularity, because this will have an impact on catalogues.

Setting the dataset/metadata granularity at the temporal instance level instead of time series level would require the generation (automatically) of a lot of metadata records and the update of catalogues in near real time. It would also make it difficult to synchronize metadata records among the GISCs, especially through harvesting processes. Such a large number of metadata records would also make it difficult for users to find the information they were seeking. For instance, a “French WMO Resolution 40 Essential SYNOP” dataset could be seen as a temporal series and, provided that the entire dataset continues to be available, the discovery metadata should be provided at this level not at temporal instance level (for example, “French WMO Resolution 40 Essential SYNOP 2016-04-07T12:00:00Z”).

It is also recommended not to blend data of different refresh rates in the same dataset, because it will not be possible to specify the update frequency in discovery metadata records;

==== Data policy and distribution scope:

A dataset shall be homogeneous in terms of data policy, including WMO distribution policy, which is described through `WMO_DistributionScopeCode`, `WMO_DataLicenseCode`, `WMO_GTSProductCategoryCode` and `MD_RestrictionCode` codelists. The Manual on WIS, Appendix C, Part C1, section 9.3 states: “The presence of more than one WMO data-policy statement in a single metadata record yields an ambiguous state; a WIS discovery metadata record describing data for global exchange shall declare only a single WMO data policy.”;

==== Spatial extent:

Except for global datasets, a coarse granularity is likely to affect the discoverability of data on the basis of a spatial criterion, especially if the areas where data are available are disjoint. For example, synoptic observations from the French Overseas Departments of Guyana, Martinique, Reunion and Guadeloupe are dispatched in different datasets.

=== Field hierarchy and cardinality

Below is a nested list of fields likely to be used in a WCMP record, together with their cardinality.

Cardinality is denoted by [x..y]. Where it is preceded by ISO, the cardinality in the WCMP will be the same. Where it is different, the cardinality for both ISO and WCMP will be appended to the element name.

As noted in paragraph 5.7.10, many optional subsections of a WCMP record contain elements that are mandatory only if that subsection is used. See, for example, the identifier, authority and title segments, as shown in lines 53–57 in the hierarchical list of fields below, where  identifier is optional [0..n] and, even if it is used, authority is also optional [0..n]; however, if authority is used, then title is mandatory [1..1].

The cardinality notation [x..y] indicates the minimum and maximum allowable times that the element may be used within that part of the hierarchy or tree.

For instance, the notation:

- [0..n] means that the element is optional, but can also be used any number of times;
- [1..2] means that it is mandatory (there must be at least one) and may be used a maximum of two times. 

```
1	MD_Metadata_ ._ .ISO[1..1] 
2	_ .fileIdentifier_ .char_ ._ . WMO[1..1] , ISO[0..1]
3	_ .language_ .char_ ._ .ISO[0..1]
4	_ .characterSet_ .CODE:MD_CharacterSetCode_ ._ .ISO[0..1]
5	_ .parentIdentifier_ .char_ ._ .ISO[0..1]
6	_ .hierarchyLevel_ .char_ ._ .ISO[0..n]
7	_ .hierarchyLevelName_ .char_ ._ .ISO[0..n]
8	
9	_ .contact_ ._ .ISO[1..n]
10	_ ._ .CI_ResponsibleParty

see lines 66-99, for all fields available for CI_ResponsibleParty

11	_ ._ ._ .individualName_ .char_ ._ .ISO[0..1]
12	_ ._ ._ .organisationName_ .char_ ._ .ISO[0..1]
13	_ ._ ._ .contactInfo_ ._ .ISO[0..1]
14	_ ._ ._ ._ . CI_Contact_ ._ .
15	_ ._ ._ ._ . _ .address_ ._ .ISO[0..1]
16	_ ._ ._ ._ ._ . _ .CI_Address_ ._ .
17	_ ._ ._ ._ ._ ._ . _ .electronicMailAddress_ .char_ ._ .ISO[0..n]
18	_ ._ ._ .role_ .CODE:CI_RoleCode_ ._ .ISO[1..1]
19	
20	_ .dateStamp_ .DATETIME_ ._ .ISO[1..1]
21	  _ .metadataStandardName_ .char_ ._ .ISO[0..1]
22	_ .metadataStandardVersion_ .char_ ._ .ISO[0..1]
23	  _ .dataSetURI_ .char_ ._ .ISO[0..1]
24	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25	_ .spatialRepresentationInfo_ ._ .ISO[0..n]
26	_ ._ .MD_GridSpatialRepresentation
27	_ ._ ._ .numberOfDimensions_ .integer_ ._ .ISO[1..1]
28	_ ._ ._ .axisDimensionProperties_ ._ .ISO[1..1]
29	_ ._ ._ ._ .MD_Dimension_ ._ .
30	_ ._ ._ ._ ._ .dimensionName_ .CODE:MD_DimensionNameTypeCode_ ._ .ISO[1..1]
31	_ ._ ._ ._ ._ .dimensionSize_ .integer_ ._ .ISO[1..1]
32	_ ._ ._ ._ ._ .resolution_ .SCALE_ ._ .ISO[0..1]
33	_ ._ ._ ._ ._ .dimensionName_ .CODE:MD_DimensionNameTypeCode_ ._ .ISO[1..1]
34	_ ._ ._ ._ ._ .dimensionSize_ .integer_ ._ .ISO[1..1]
35	_ ._ ._ ._ ._ .resolution_ .SCALE_ ._ .ISO[0..1]
36	_ ._ ._ .cellGeometry_ .CODE:MD_CellGeometryCode_ ._ .ISO[1..1]
37	_ ._ ._ .transformationParameterAvailability_ .Boolean_ ._ .ISO[1..1]
38	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
39	
40	_ .identificationInfo_ ._ .ISO[1..n]
41	_ ._ .MD_DataIdentification_ .
42	
43	_ ._ ._ .citation_ ._ .ISO[1..1]
44	_ ._ ._ ._ .CI_Citation_ ._ .
45	_ ._ ._ ._ ._ .title_ .char_ ._ .ISO[1..1]
46	_ ._ ._ ._ ._ .alternateTitle_ .char_ ._ .ISO[0..n]
47	_ ._ ._ ._ ._ .DATE_ ._ .ISO[1..n]
48	_ ._ ._ ._ ._ ._ .CI_Date_ .
49	_ ._ ._ ._ ._ ._ ._ .DATE_ .DATETIME_ ._ .ISO[1..1]
50	_ ._ ._ ._ ._ ._ ._ .dateType_ .CODE:CI_DateTypeCode_ ._ .ISO[1..1]
51	_ ._ ._ ._ ._ .edition_ .char_ ._ .ISO[0..1]
52	
53	_ ._ ._ ._ ._ .identifier_ ._ .ISO[0..n]
54	_ ._ ._ ._ ._ ._ .MD_Identifier_ ._ .
55	_ ._ ._ ._ ._ ._ ._ .authority_ ._ .ISO[0..1]
56	_ ._ ._ ._ ._ ._ ._ ._ .CI_Citation_ ._ .

see lines 43-111, for all fields available for CI_Citation

57	_ ._ ._ ._ ._ ._ ._ ._ ._ .title_ .char_ ._ .ISO[1..1]
58	_ ._ ._ ._ ._ ._ ._ ._ ._ .alternateTitle_ .char_ ._ .ISO[0..n]
59	_ ._ ._ ._ ._ ._ ._ ._ ._ .DATE_ ._ .ISO[1..n]
60	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_Date_ .
61	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .DATE_ .DATE_ ._ .ISO[1..1]
62	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .dateType_ .CODE:CI_DateTypeCode_ ._ .ISO[1..1]
63	_ ._ ._ ._ ._ ._ ._ .code_ .char_ ._ .ISO[1..1]
64	
65	_ ._ ._ ._ ._ .citedResponsibleParty_ ._ .ISO[0..n]  
66	_ ._ ._ ._ ._ ._ .CI_ResponsibleParty_ ._ .
67	_ ._ ._ ._ ._ ._ ._ .individualName_ .char_ ._ .ISO[0..1] *C
68	_ ._ ._ ._ ._ ._ ._ .organisationName_ .char_ ._ .ISO[0..1] *C
69	_ ._ ._ ._ ._ ._ ._ .positionName_ .char_ ._ .ISO[0..1] *C
70	
71	_ ._ ._ ._ ._ ._ ._ .contactInfo_ ._ .ISO[0..1]
72	_ ._ ._ ._ ._ ._ ._ ._ .CI_Contact_ ._ .
73	
74	_ ._ ._ ._ ._ ._ ._ ._ ._ .phone_ ._ .ISO[0..1]
75	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_Telephone_ ._ .
76	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .voice_ .char_ ._ .ISO[0..n]
77	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .facsimile_ .char_ ._ .ISO[0..n]
78	
79	_ ._ ._ ._ ._ ._ ._ ._ ._ .address_ ._ .ISO[0..1]
80	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_Address_ ._ .
81	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .deliveryPoint_ .char_ ._ .ISO[0..n]
82	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .city_ .char_ ._ .ISO[0..1]
83	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .administrativeArea_ .char_ ._ .ISO[0..1]
84	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .postalCode_ .char_ ._ .ISO[0..1]
85	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .country_ .char_ ._ .ISO[0..1]
86	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .electronicMailAddress_ .char_ ._ .ISO[0..n]
87	
88	_ ._ ._ ._ ._ ._ ._ ._ ._ .onlineResource_ ._ .ISO[0..1]
89	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_OnlineResource_ ._ .
90	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .linkage_ .URL_ ._ .ISO[1..1]
91	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .protocol_ .char_ ._ .ISO[0..1]
92	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .applicationProfile_ .char_ ._ .ISO[0..1]
93	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .name_ .char_ ._ .ISO[0..1]
94	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .description_ .char_ ._ .ISO[0..1]
95	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .function_ .CODE:CI_OnLineFunctionCode_ ._ .ISO[0..1]
96	
97	_ ._ ._ ._ ._ ._ ._ ._ ._ .hoursOfService_ .char_ ._ .ISO[0..1]
98	_ ._ ._ ._ ._ ._ ._ ._ ._ .contactInstructions_ .char_ ._ .ISO[0..1]
99	_ ._ ._ ._ ._ ._ ._ .role_ .CODE:CI_RoleCode_ [1..1].
100	
101	_ ._ ._ ._ ._ .presentationForm_ .CODE:CI_PresentationFormCode_ ._ .ISO[0..n]
102	
103	_ ._ ._ ._ ._ .series_ ._ .ISO[0..1]
104	_ ._ ._ ._ ._ ._ .CI_Series_ .
105	_ ._ ._ ._ ._ ._ ._ .name_ .char_ ._ .ISO[0..1]
106	_ ._ ._ ._ ._ ._ ._ .issueIdentification_ .char_ ._ .ISO[0..1]
107	_ ._ ._ ._ ._ ._ ._ .page_ .char_ ._ .ISO[0..1]
108	_ ._ ._ ._ ._ .otherCitationDetails_ .char_ ._ .ISO[0..1]
109	_ ._ ._ ._ ._ .collectiveTitle_ .char_ ._ .ISO[0..1]
110	_ ._ ._ ._ ._ .ISBN_ .char_ ._ .ISO[0..1]
111	_ ._ ._ ._ ._ .ISSN_ .char_ ._ .ISO[0..1]
112	
113	
114	_ ._ ._ .abstract_ .char_ ._ .ISO[1..1]
115	_ ._ ._ .purpose_ .char_ ._ .ISO[0..1]
116	_ ._ ._ .credit_ .char_ ._ .ISO[0..n]
117	_ ._ ._ .status_ .CODE:MD_ProgressCode_ ._ .ISO[0..n]
118	
119	_ ._ ._ .pointOfContact_ ._ .ISO[0..n]
120	_ ._ ._ ._ .CI_ResponsibleParty_ ._ .    
121	_ ._ ._ ._ ._ .individualName_ .char_ ._ .ISO[0..1]
122	_ ._ ._ ._ ._ .organisationName_ .char_ ._ .ISO[0..1]
123	_ ._ ._ ._ ._ .positionName_ .char_ ._ .ISO[0..1]
124	_ ._ ._ ._ ._ .contactInfo_ ._ .ISO[0..1]
125	_ ._ ._ ._ ._ ._ .CI_Contact_ ._ .
126	_ ._ ._ ._ ._ ._ ._ .phone_ ._ .ISO[0..1]
127	_ ._ ._ ._ ._ ._ ._ ._ .CI_Telephone_ ._ .
128	_ ._ ._ ._ ._ ._ ._ ._ ._ .voice_ .char_ ._ .ISO[0..1]
129	_ ._ ._ ._ ._ ._ ._ ._ ._ .facsimile_ .char_ ._ .ISO[0..1]
130	_ ._ ._ ._ ._ ._ ._ .address_ ._ .ISO[0..1]
131	_ ._ ._ ._ ._ ._ ._ ._ .CI_Address_ ._ .
132	_ ._ ._ ._ ._ ._ ._ ._ ._ .deliveryPoint_ .char_ ._ .ISO[0..1]
133	_ ._ ._ ._ ._ ._ ._ ._ ._ .electronicMailAddress_ .char_ ._ .ISO[0..1]
134	_ ._ ._ ._ ._ .role_ .CODE:CI_RoleCode_ ._ .ISO[1..1]
135	
136	_ ._ ._ .resourceMaintenance_ ._ .ISO[0..n]
137	_ ._ ._ ._ .MD_MaintenanceInformation_ .
138	_ ._ ._ ._ ._ .maintenanceAndUpdateFrequency_ .
           CODE: MD_MaintenanceFrequencyCode_ ._ .ISO[1..1]
139	_ ._ ._ ._ ._ .userDefinedMaintenanceFrequency_ .TM_PeriodDuration_ ._ .ISO[0..1]
140	_ ._ ._ ._ ._ .updateScopeDescription_ ._ .ISO[0..n]
141	_ ._ ._ ._ ._ ._ .MD_ScopeDescription_ .
142	_ ._ ._ ._ ._ ._ ._ .dataset_ .char_ ._ .ISO[1..1]
143	_ ._ ._ ._ ._ .maintenanceNote_ .char_ ._ .ISO[0..n]
144	
145	_ ._ ._ .graphicOverview_ ._ .ISO[0..n]
146	_ ._ ._ ._ .MD_BrowseGraphic_ .
147	_ ._ ._ ._ ._ .fileName_ .char_ ._ .ISO[1..1]
148	_ ._ ._ ._ ._ .fileDescription_ .char_ ._ .ISO[0..1]
149	_ ._ ._ ._ ._ .fileType_ .char_ ._ .ISO[0..1]
150	
151	_ ._ ._ .descriptiveKeywords_ ._ WMO[1..n]   .ISO[0..n]
152	_ ._ ._ ._ .MD_Keywords_ .
153	_ ._ ._ ._ ._ .keyword_ .char_ ._ .ISO[1..n]
154	_ ._ ._ ._ ._ .type_ .CODE:MD_KeywordTypeCode_ ._ .ISO[0..1]
155	_ ._ ._ ._ ._ .thesaurusName_ ._ .ISO[0..1]
156	_ ._ ._ ._ ._ ._ .CI_Citation_ ._ .

see lines 43-111, for all fields available for CI_Citation

157	_ ._ ._ ._ ._ ._ ._ .title_ .char_ ._ .ISO[1..1]
158	_ ._ ._ ._ ._ ._ ._ .DATE_ ._ .ISO[1..1]
159	_ ._ ._ ._ ._ ._ ._ ._ .CI_Date_ ._ .
160	_ ._ ._ ._ ._ ._ ._ ._ ._ .DATE_ .DATE_ ._ .ISO[1..1]
161	_ ._ ._ ._ ._ ._ ._ ._ ._ .dateType_ .CODE:CI_DateTypeCode_ ._ .ISO[1..1]
162	
163	_ ._ ._ .resourceSpecificUsage_ ._ .ISO[0..n]
164	_ ._ ._ ._ .MD_Usage_ .
165	_ ._ ._ ._ ._ .specificUsage_ .char_ ._ .ISO[1..1]
166	_ ._ ._ ._ ._ .userDeterminedLimitations_ .char_ ._ .ISO[0..n]
167	_ ._ ._ ._ ._ .userContactInfo_ ._ .ISO[1..n]
168	_ ._ ._ ._ ._ ._ .CI_ResponsibleParty_ ._ .

see lines 66-99, for all fields available for CI_ResponsibleParty

169	 _ ._ ._ ._ ._ ._ ._ .individualName_ .char_ ._ .ISO[0..1]
170	_ ._ ._ ._ ._ ._ ._ .organisationName_ .char_ ._ .ISO[0..1]
171	_ ._ ._ ._ ._ ._ ._ .role_ .CODE:CI_RoleCode_ ._ .ISO[1..1]
172	
173	_ ._ ._ .resourceConstraints_ ._ .ISO[0..n]
174	_ ._ ._ ._ .MD_Constraints_ . ISO[0..n]
175	_ ._ ._ ._ ._ .useLimitation_ ._ .ISO[0..n]
176	_ ._ ._ ._ .MD_LegalConstraints_ . ISO[0..n]
177	_ ._ ._ ._ ._ .useLimitation_ .char_ ._ .ISO[0..n]
178	_ ._ ._ ._ ._ .accessConstraints_ .CODE:MD_RestrictionCode_ ._ .ISO[0..n]
179	_ ._ ._ ._ ._ .accessConstraints_ .CODE:MD_RestrictionCode_ ._ .ISO[0..n]
180	_ ._ ._ ._ ._ .useConstraints_ .CODE:MD_RestrictionCode_ ._ .ISO[0..n]
181	_ ._ ._ ._ ._ .useConstraints_ .CODE:MD_RestrictionCode_ ._ .ISO[0..n]
182	_ ._ ._ ._ ._ .otherConstraints_ .char_ ._ .ISO[0..n]
183	_ ._ ._ ._ ._ .otherConstraints_ .char_ ._ .ISO[0..n]
184	_ ._ ._ ._ .MD_SecurityConstraints_ . ISO[0..n]
185	_ ._ ._ ._ ._ .useLimitation_ .char_ ._ .ISO[0..n]
186	_ ._ ._ ._ ._ .classification_ .CODE:MD_ClassificationCode_ ._ .ISO[1..1]
187	_ ._ ._ ._ ._ .userNote_ .char_ ._ .ISO[0..1]
188	_ ._ ._ ._ ._ .classificationSystem_ .char_ ._ .ISO[0..1]
189	_ ._ ._ ._ ._ .handlingDescription_ .char_ ._ .ISO[0..1]
190	
191	_ ._ ._ .aggregationInfo_ ._ .ISO[0..n]
192	_ ._ ._ ._ .MD_AggregateInformation_ .
193	
194	_ ._ ._ ._ ._ .aggregateDataSetName_ ._ .ISO[0..1]
195	_ ._ ._ ._ ._ ._ .CI_Citation_ ._ .

see lines 43-111, for all fields availablefor CI_Citation

196	_ ._ ._ ._ ._ ._ ._ .title_ .char_ ._ .ISO[1..1]
197	_ ._ ._ ._ ._ ._ ._ .DATE_ ._ .ISO[1..1]
198	_ ._ ._ ._ ._ ._ ._ ._ .CI_Date_ ._ .
199	_ ._ ._ ._ ._ ._ ._ ._ ._ .DATE_ . DATE _ ._ .ISO[1..1]
200	_ ._ ._ ._ ._ ._ ._ ._ ._ .dateType_ .CODE:CI_DateTypeCode_ ._ .ISO[1..1]
201	
202	_ ._ ._ ._ ._ .aggregateDataSetIdentifier_ ._ .ISO[0..1]
203	_ ._ ._ ._ ._ ._ .MD_Identifier_ . 
204	_ ._ ._ ._ ._ ._ ._ .authority_ ._ .ISO[0..1]
205	_ ._ ._ ._ ._ ._ ._ ._ .CI_Citation_ ._ .

see lines 43-111, for all fields available for CI_Citation

206	_ ._ ._ ._ ._ ._ ._ ._ ._ .title_ .char_ ._ .ISO[1..1]
207	_ ._ ._ ._ ._ ._ ._ ._ ._ .DATE_ ._ .ISO[1..1]
208	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_Date_ ._ .
209	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .DATE_ . DATE_ ._ .ISO[1..1]
210	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .dateType_ .CODE:CI_DateTypeCode_ ._ .ISO[1..1]
211	_ ._ ._ ._ ._ ._ ._ .code_ .char_ ._ .ISO[1..1]
212	
213	_ ._ ._ ._ ._ .associationType_ .CODE:DS_AssociationTypeCode_ ._ .ISO[1..1]
214	_ ._ ._ ._ ._ .initiativeType_ .CODE:DS_InitiativeTypeCode_ ._ .ISO[0..1]
215	
216	_ ._ ._ .spatialRepresentationType
217	_ ._ ._ ._ .MD_SpatialRepresentationTypeCode 
	                       CODE: MD_SpatialRepresentationTypeCode  ISO[0..n]
218	
219	_ ._ ._ .spatialResolution_ ._ .ISO[0..n]
220	_ ._ ._ ._ .MD_Resolution_ ._ .ISO[ ..]
221	_ ._ ._ ._ ._ .equivalentScale_ ._ .ISO[1..1]
222	_ ._ ._ ._ ._ ._ .MD_RepresentativeFraction_ .
223	_ ._ ._ ._ ._ ._ ._ .denominator_ .integer_ ._ .ISO[1..1]
224	
225	_ ._ ._ .language_ .char_ ._ .ISO[1..n]
226	_ ._ ._ .characterSet_ .CODE:MD_CharacterSetCode_ ._ .ISO[0..n]
227	_ ._ ._ .topicCategory_ .CODE:MD_TopicCategoryCode_ ._ .WMO[1..n]   ISO[0..n]
228	_ ._ ._ .environmentDescription_ .char_ ._ .ISO[0..1]
229	
230	_ ._ ._ .extent_ ._ .ISO[0..n]
231	_ ._ ._ ._ .EX_Extent_ .
232	_ ._ ._ ._ ._ .description_ .char_ ._ .ISO[0..1]
233	_ ._ ._ ._ ._ .geographicElement_ ._. .ISO[0..n] (Mandatory, if data is geospatial)
234	_ ._ ._ ._ ._ . _ . EX_GeographicBoundingBox_
235	_ ._ ._ ._ ._ . _ ._ .westBoundLongitude_ .DECIMAL_ ._ .ISO[1..1]
236	_ ._ ._ ._ ._ . _ ._ .eastBoundLongitude_ . DECIMAL_ ._ .ISO[1..1]
237	_ ._ ._ ._ ._ . _ ._ .southBoundLatitude_ . DECIMAL_ ._ .ISO[1..1]
238	_ ._ ._ ._ ._ . _ ._ .northBoundLatitude_ . DECIMAL_ ._ .ISO[1..1]
239	
240	
241	_ ._ ._ ._ ._ .geographicElement_ . ISO[0..n]
242	_ ._ ._ ._ ._ ._ .EX_GeographicDescription_ .
243	_ ._ ._ ._ ._ ._ ._ .extentTypeCode_ ._ .Boolean_ ._ .ISO[0..1]
244	_ ._ ._ ._ ._ ._ ._ .geographicIdentifier_ ._ .ISO[1..1]
245	_ ._ ._ ._ ._ ._ ._ ._ .MD_Identifier_ .
246	_ ._ ._ ._ ._ ._ ._ ._ ._ .code_ .char_ ._ .ISO[1..1]
247	
248	
249	_ ._ ._ ._ ._ .temporalElement_ ._ .ISO[0..n]
250	_ ._ ._ ._ ._ ._ .EX_TemporalExtent_ .
251	_ ._ ._ ._ ._ ._ ._ .extent_ ._ .ISO[1..1]
252	
253	_ ._ ._ .supplementalInformation_ .char_ ._ .ISO[0..1]
254	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
255	
256	_ .referenceSystemInfo_ ._ .ISO[0..n]
257	_ ._ .MD_ReferenceSystem_ .
258	_ ._ ._ .referenceSystemIdentifier_ ._ .ISO[0..1]
259	_ ._ ._ ._ .RS_Identifier_ .
260	_ ._ ._ ._ ._ .authority_ ._ .ISO[0..1]
261	_ ._ ._ ._ ._ .code_ .char_ ._ .ISO[1..1]
262	_ ._ ._ ._ ._ .codeSpace_ .char_ ._ .ISO[0..1]
263	_ ._ ._ ._ ._ .version_ .char_ ._ .ISO[0..1]
264	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
265	
266	_ .contentInfo_ ._ .ISO[0..n]
267	_ ._ .MD_CoverageDescription_ .
268	_ ._ ._ .attributeDescription_ ._ .ISO[1..1]
269	_ ._ ._ ._ .RecordType_ ._ .
270	_ ._ ._ .contentType_ .CODE:MD_CoverageContentTypeCode_ ._ .ISO[1..1]
271	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
272	
273	_ .distributionInfo_ ._ .ISO[0..1]
274	_ ._ .MD_Distribution_ .
275	_ ._ ._ .distributionFormat_ ._ .ISO[0..n]
276	_ ._ ._ ._ .MD_Format_ .
277	_ ._ ._ ._ ._ .name_ .char_ ._ .ISO[1..1]
278	_ ._ ._ ._ ._ .version_ .char_ ._ .ISO[1..1]
279	_ ._ ._ ._ ._ .amendmentNumber_ .char_ ._ .ISO[0..1]
280	_ ._ ._ ._ ._ .specification_ .char_ ._ .ISO[0..1]
281	_ ._ ._ ._ ._ .fileDecompressionTechnique_ .char_ ._ .ISO[0..1]
282	
283	_ ._ ._ ._ ._ .formatDistributor_ ._ .ISO[0..n]
284	_ ._ ._ ._ ._ ._ .MD_Distributor_ .
285	_ ._ ._ ._ ._ ._ ._ .distributorContact_ ._ .ISO[1..1]
286	_ ._ ._ ._ ._ ._ ._ ._ .CI_ResponsibleParty_ . 

see lines 66-99, for all fields available for CI_ResponsibleParty

287	_ ._ ._ ._ ._ ._ ._ ._ ._ .individualName_ .char_ ._ .ISO[0..1]
288	_ ._ ._ ._ ._ ._ ._ ._ ._ .organisationName_ .char_ ._ .ISO[0..1]
289	_ ._ ._ ._ ._ ._ ._ ._ ._ .role_ .CODE:CI_RoleCode_ ._ .ISO[1..1]
290	_ ._ ._ ._ ._ ._ ._ .distributorTransferOptions_ ._ .ISO[0..n]
291	_ ._ ._ ._ ._ ._ ._ ._ .MD_DigitalTransferOptions_ .
292	_ ._ ._ ._ ._ ._ ._ ._ ._ .unitsOfDistribution_ .char_ ._ .ISO[0..1]
293	_ ._ ._ ._ ._ ._ ._ ._ ._ .transferSize_ .Real_ ._ .ISO[0..1]
294	
295	_ ._ ._ ._ ._ ._ ._ ._ ._ .onLine_ ._ .ISO[0..n]
296	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_OnlineResource_ .
297	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .linkage_ .URL_ ._ .ISO[1..1]
298	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .protocol_ .char_ ._ .ISO[0..1]
299	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .name_ .char_ ._ .ISO[0..1]
300	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .description_ .char_ ._ .ISO[0..1]
301	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ ._ .function_ .CODE: CI_OnLineFunctionCode_ ._ .ISO[0..1]
302	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
303	
304	_ .dataQualityInfo_ ._ .ISO[0..n]
305	_ ._ .DQ_DataQuality_ .
306	_ ._ ._ .scope_ ._ .ISO[1..1]
307	_ ._ ._ ._ .DQ_Scope_ .
308	_ ._ ._ ._ ._ .level_ .CODE:MD_ScopeCode_ ._ .ISO[1..1]
309	_ ._ ._ ._ ._ .extent_ .
310	_ ._ ._ ._ ._ .levelDescription_ ._ .ISO[0..n]
311	_ ._ ._ ._ ._ ._ .MD_ScopeDescription_ .
312	_ ._ ._ ._ ._ ._ ._ .dataset_ .char_ ._ .ISO[1..1]
313	_ ._ ._ .lineage_ ._ .ISO[0..1]
314	_ ._ ._ ._ .LI_Lineage_ .
315	_ ._ ._ ._ ._ .statement_ .char_ ._ .ISO[0..1]
316	
317	_ ._ ._ ._ ._ .processStep_ ._ .ISO[0..n]
318	_ ._ ._ ._ ._ ._ .LI_ProcessStep_ .
319	_ ._ ._ ._ ._ ._ ._ .description_ .char_ ._ .ISO[1..1]
320	_ ._ ._ ._ ._ ._ ._ .rationale_ .char_ ._ .ISO[0..1]
321	_ ._ ._ ._ ._ ._ ._ .source_ ._ .ISO[0..n]
322	_ ._ ._ ._ ._ ._ ._ ._ .LI_Source_ .
323	_ ._ ._ ._ ._ ._ ._ ._ ._ .description_ .char_ ._ .ISO[0..1]
324	_ ._ ._ ._ ._ ._ ._ ._ ._ .sourceCitation_ ._ .ISO[0..1]
325	_ ._ ._ ._ ._ ._ ._ ._ ._ ._ .CI_Citation_ ._ . 
326	
327	_ ._ ._ ._ ._ .source_ ._ .ISO[0..n]
328	_ ._ ._ ._ ._ ._ .LI_Source_ .
329	_ ._ ._ ._ ._ ._ ._ .description_ .char_ ._ .ISO[0..1]
330	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
331	
332	_ .metadataConstraints_ ._ .ISO[0..n]
333	_ ._ .MD_Constraints_ .
334	_ ._ ._ .useLimitation_ .char_ ._ .ISO[0..n]
335	_ ._ .MD_LegalConstraints_ .
336	_ ._ ._ .useLimitation_ .char_ ._ .ISO[0..n]
337	_ ._ ._ .accessConstraints_ .CODE: MD_RestrictionCode_ ._ .ISO[0..n]
338	_ ._ ._ .useConstraints_ .CODE: MD_RestrictionCode
339	_ ._ ._ .otherConstraints_ .char_ ._ .ISO[0..n]
340	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
341	
342	_ .applicationSchemaInfo_ ._ .ISO[0..n]
343	_ ._ .MD_ApplicationSchemaInformation_ .
344	_ ._ ._ .name_ ._ .ISO[1..1]
345	_ ._ ._ ._ .CI_Citation_ ._ . 

see lines 43-111, for all fields available for CI_Citation

346	_ ._ ._ .schemaLanguage_ .char_ .
347	_ ._ ._ .constraintLanguage_ .char_ ._ .ISO[1..1]
348	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
349	
350	_ .metadataMaintenance_ .
351	_ ._ .MD_MaintenanceInformation_ ._ .ISO[0..1]
352	_ ._ ._ .maintenanceAndUpdateFrequency_ . CODE:MD_MaintenanceFrequencyCode_ ._ .ISO[1..1]
353	_ ._ ._ .dateOfNextUpdate_ .DATE_ ._ .ISO[1..1]
354	_ ._ ._ .userDefinedMaintenanceFrequency_ .PERIODDURATION_ ._ .ISO[0..1]
355	_ ._ ._ .updateScope_ .CODE:MD_ScopeCode_ ._ .ISO[0..1]
356	_ ._ ._ .updateScopeDescription_ ._ .ISO[0..n]
357	_ ._ ._ ._ .MD_ScopeDescription_ ._ .ISO[0..n]
358	_ ._ ._ ._ ._ .dataset_ .char_ .
359	_ ._ ._ .maintenanceNote_ .char_ ._ .ISO[1..1]
360	   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
