== Overview

=== Purpose

This document is intended to define Key Performance Indicators (KPIs) in
support of the WMO Core Metadata Profile (WCMP).  KPIs provide measurable,
value added quality assessment rules over and above syntactic and schematic
rulesets put forth by WCMP and ISO 19115:2003/19139:2007.

The core driver of WCMP KPIs is continuous improvement and useability of
discovery metadata as part of the https://community.wmo.int/activity-areas/wmo-information-system-wis[WMO Information System (WIS)].

=== Scope

This document is bound to the WCMP 1.3 specification and codelists. All
other metadata specifications or representations are not in scope.

=== Audience

The target stakeholder audiences for this document include (but are not limited to):

* Metadata providers (NCs, DCPCs)
* Metadata consumers (GISCs)
* WMO World Data Centres (WDCs)
* GAW World Data Centres (WDCs)
* WMO WIS Operations and Monitoring
* Metadata implementors (generation, ingest)

=== How to use

The KPIs in this document are designed to help metadata providers in the
curation of discovery metadata, as well as GISCs to measure the quality
of metadata from NCs and DCPCs.

In order to improve quality:

* providers should use the KPIs to build into their metadata generation
* consumers should use the KPIs in order to quality assess discovery metadata
  and provide subsequent feedback to providers

=== Scoring

Each KPI assesses a number of criteria asssociated with metadata quality,
resulting in a raw score, as well as a percentage. This approach is
implemented so as to apply weighted scoring as required by a scoring rubric.

=== Reference implementation

The TT-WISMD maintains link:https://github.com/wmo-im/pywcmp[pywcmp], as the
reference WCMP validation utility which includes:

* validation against WMO Core Metadata Profile 1.3, specifically Part 2,
  Section 2
* validation against the KPIs described in this document

Documentation on installation, configuration and usage can be found on the
pywcmp website.

pywcmp is provided as a resource to the community, under continuous
improvement. Contributions are welcome and can be facilited via TT-WISMD.

=== Codelists rules

WMO and ISO codelists currently exist in numerous locations on the Internet.
The authoritative code locations that should be used when validating shall be:

* WMO codelists: https://wis.wmo.int/2012/codelists/WMOCodeLists.xml
* ISO codelists: https://standards.iso.org/iso/19139/resources/gmxCodelists.xml

=== Conventions

==== Symbols and abbreviated terms

.Symbols and abbreviated terms
|===
|Abbreviation |Term

|AJAX
|Asynchronous JavaScript and XML

|CSV
|Comma-separated values

|DCPC
|Data Collection and Production Centres

|DOI
|Digital Object Identifier

|GAW
|Global Atmospheric Watch

|GISC
|Global Information System Centre

|GML
|Geography Markup Language

|GTS
|Global Telecommunication System

|HTML
|Hypertext Markup Language

|HTTP
|Hypertext Transfer Protocol

|HTTPS
|Hypertext Transfer Protocol Secure

|INSPIRE
|Infrastructure for Spatial Information in the European Community

|ISO
|Internatioal Organization for Standardization

|MIME
|Multipurpose Internet Mail Extensions

|NC
|National Centre

|OGC
|Open Geospatial Consortium

|pywcmp
|WMO implementation of WCMP validation

|URL
|Uniform Resource Locator

|WCMP
|WMO Core Metadata Profile

|WDC
|World Data Centre

|WIS
|WMO Information System

|WMO
|World Meteorological Organization

|XHR
|XMLHttpRequest

|XML
|eXtensible Markup Language

|===

