== KPI-1: WCMP 1.3, Part 2 Compliance

=== Measurement

Most requirements specified in the abstract test suite in Manual on WIS (WMO-No. 1060), Part C2, section 2.

=== Rational for measurement

Compliance with the requirements of the abstract test suite ensures that the metadata record is valid and supports base level information for discovery and access.  

=== Rules

WCMP 1.3, Part C2, 2.1 Abstract tests for XML encoding

|===
|Rule |Score

|Requirement 6.1.1: Each WIS Discovery Metadata record shall validate without error against the XML schemas defined in ISO/TS 19139:2007.
|Pass/Fail

a|Requirement 8.1.1: Each WIS Discovery Metadata record shall include one `gmd:MD_Metadata/gmd:fileIdentifier` attribute.
|1

a|Requirement 8.2.1: Each WIS Discovery Metadata record shall include at least one keyword from the `WMO_CategoryCode` code list.
|1

a|Requirement 8.2.2: Keywords from `WMO_CategoryCode` code list shall be defined as keyword type `theme`.
|1

a|Requirement 8.2.3: All keywords sourced from a particular keyword thesaurus shall be grouped into a single instance of the `MD_Keywords` class.
|1

|Requirement 8.2.4: Each WIS Discovery Metadata record describing geographic data shall include the description of at least one geographic bounding box defining the spatial extent of the data.
|1

a|Requirement 9.1.1: A WIS Discovery Metadata record describing data for global exchange via the WIS shall indicate the scope of distribution using the keyword `GlobalExchange` of type `dataCenter` from thesaurus `WMO_DistributionScopeCode`.
|1

a|Requirement 9.2.1: A WIS Discovery Metadata record describing data for global exchange via the WIS shall have a `gmd:MD_Metadata/gmd:fileIdentifier` attribute formatted as follows (where `{uid}` is a unique identifier derived from the GTS bulletin or file name): `urn:x-wmo:md:int.wmo.wis::{uid}`.
|1

a|Requirement 9.3.1: A WIS Discovery Metadata record describing data for global exchange via the WIS shall indicate the WMO Data License as Legal Constraint (type: `gmd:otherConstraints`) using one and only one term from the `WMO_DataLicenseCode` code list.
|1

a|Requirement 9.3.2: A WIS Discovery Metadata record describing data for global exchange via the WIS shall indicate the GTS Priority as Legal Constraint (type: `gmd:otherConstraints`) using one and only one term from the `WMO_GTSProductCategoryCode` code list.
|1
|===

*Total possible score: 9 (100%)*

=== Guidance to score well on this assessment

Use WCMP templates and/or tools to generate the metadata record (e.g. Excel to WIS).

=== WCMP element(s)
Elements specified in the WCMP 1.3, Part C2 - Abstract Test Suite, Data Dictionary and Code Lists in the Manual on WIS (WMO-No. 1060).
