== KPI-4: Temporal information

=== Measurement

The temporal extent, frequency of resource updates and status elements are present. 

=== Rationale for measurement

Temporal information is a significant characteristic of WMO
data and it is critical for users to know the time periods that are
covered by the products, how often new products are available and the status.

=== Rules

.Temporal information implementation rules
|===
|Rule |Score

|The temporal extent elements are present.
|1

|The begin position and end position elements are present in the temporal extent.
|1

|The begin date time is less than or equal to the end date time.
|1

|The frequency of resource updates elements are present.
|1

|The status element is present.
|1
|===

*Total possible score: 5 (100%)*

=== Guidance to score well on this assessment

FIX this section: 
Ensure that the Temporal Extent and the Update Frequency is present in the metadata record.

It is also recommended to identify a dataset status / progress using the gmd:MD_ProgressCode codelist. The following example provides an ongoing dataset progress/status:

```xml
  <gmd:status>
    <gmd:MD_ProgressCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ProgressCode" codeSpace="ISOTC211/19115" codeListValue="onGoing">onGoing</gmd:MD_ProgressCode>
  </gmd:status>
```

If it is not relevant or necessary to provide information regarding the data
update frequency, `gmd:MD_MaintenanceFrequencyCode` can be set to `asNeeded`:

==== Guidelines and examples in this guide
* 5.8.1.5 Temporal extent
* 5.8.1.13 Frequency of resource updates

=== WCMP Element(s)

* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent`
* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:resourceMaintenance//gmd:maintenanceAndUpdateFrequency`
* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:status`
