== KPI-{counter:kpi}: Temporal information

=== Status

Approved

=== WCMP Element(s)

* `/gmd:MD_Metadata/gmd:identification//gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent`
* `/gmd:MD_Metadata/gmd:identification//gmd:resourceMaintenance//gmd:maintenanceAndUpdateFrequency`

=== What is being measured

* Temporal extent: This element describes the period of time that the available product covers
* Data update frequency: The temporal frequency at which the data is updated (i.e. every x hours, days, etc.)

=== Rationale for measurement

Temporal information is a significant characteristic of weather/climate/water
data and as such is critical for users to know which period(s) of time is/are
covered by products and how often new products are received.

=== Rules for implementation

The TemporalExtent is defined in `gmd:temporalElement`:

```xml
<gmd:identificationInfo>
  ...
  <gmd:temporalElement>
    <gmd:EX_TemporalExtent id="boundingTemporalExtent">
      <gmd:extent>
        <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
          <gml:beginPosition>2005-10-01</gml:beginPosition>
          <gml:endPosition>2014-10-20</gml:endPosition>
        </gml:TimePeriod>
      </gmd:extent>
    </gmd:EX_TemporalExtent>
  </gmd:temporalElement>
  ...
</gmd:identificationInfo>
```

In the case of an ongoing dataset with a known start date, but no known end
date can be defined, the end date must be defined as `now`.  For instance,
where a dataset is from 2005-10-01 onwards:

```xml
<gmd:identificationInfo>
  ...
  <gmd:temporalElement>
     <gmd:EX_TemporalExtent id="temporalExtent">
       <gmd:extent>
         <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
           <gml:beginPosition>2005-10-01</gml:beginPosition>
           <gml:endPosition indeterminatePosition="now"/>
         </gml:TimePeriod>
       </gmd:extent>
     </gmd:EX_TemporalExtent>
  </gmd:temporalElement>
</gmd:temportalElement>
```

It is also recommended to identify a dataset status / progress using the `gmd:MD_ProgressCode`
codelist.  The following example provides an ongoing dataset progress/status:

```xml
<gmd:identificationInfo>
  ...
  <gmd:status>
    <gmd:MD_ProgressCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ProgressCode" codeSpace="ISOTC211/19115" codeListValue="onGoing">onGoing</gmd:MD_ProgressCode>
  </gmd:status>
</gmd:identificationInfo>
```

The Data Update Frequency is defined in `gmd:maintenanceAndUpdateFrequency`:

Below is an example of a GTS bulletin which is updated every 6 hours.

```xml
<gmd:identificationInfo>
  ...
  <gmd:resourceMaintenance>
    <gmd:MD_MaintenanceInformation>
      <gmd:maintenanceAndUpdateFrequency>
        <gmd:MD_MaintenanceFrequencyCode codeListValue="irregular" codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_MaintenanceFrequencyCode"/>
      </gmd:maintenanceAndUpdateFrequency>
      <gmd:userDefinedMaintenanceFrequency>
        <gts:TM_PeriodDuration>PT6H</gts:TM_PeriodDuration>
      </gmd:userDefinedMaintenanceFrequency>
      <gmd:maintenanceNote>
        <!-- DRAFT – Guidance on WIS Discovery Metadata (following CBS-16), p38 -->
        <gco:CharacterString>Instances of bulletin SIKB20NGTT are available every 6 hours starting at 03 UTC.</gco:CharacterString>
      </gmd:maintenanceNote>
    </gmd:MD_MaintenanceInformation>
  </gmd:resourceMaintenance>
  ...
</gmd:identificationInfo>
```

If it is not relevant or necessary to provide information regarding the data
update frequency, `gmd:MD_MaintenanceFrequencyCode` can be set to `asNeeded`:

```xml
<gmd:identificationInfo>
  ...
  <gmd:resourceMaintenance>
      <gmd:MD_MaintenanceInformation>
        <gmd:maintenanceAndUpdateFrequency>
          <gmd:MD_MaintenanceFrequencyCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_MaintenanceFrequencyCode" codeListValue="asNeeded"/>
        </gmd:maintenanceAndUpdateFrequency>
      </gmd:MD_MaintenanceInformation>
  </gmd:resourceMaintenance>
  ...
</gmd:identificationInfo>
```

.Temporal information implementation rules

|===
|Rule |Score

|The Temporal Extent is defined
|1

|The Temporal Extent contains begin and end components
|1

|The begin date time is less than or equal to the end date time
|1

|The Data Update Frequency is defined
|1

|The Data Status is defined
|1
|===

*Total possible score: 5 (100%)*

=== Guidance to score well on this assessment

Ensure that the Temporal Extent and the Update Frequency is defined in the metadata record.

