== KPI-5: WMOEssential data links

=== Measurement

Ensure that distribution URLs are included when the DataLicenseCode of
`WMOEssential` is indicated in the constraint section.

=== Rationale for measurement

All `WMOEssential` data should have 1..n distribution links to the data.

=== Rules


.WMOEssential data links implementation rules
|===
|Rule |Score

a|`DataLicenseCode` is `WMOEssential` and 1..n distribution links are present
|1

|===

*Total possible score: 1 (100%)*

=== Guidance

==== XML Examples

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode_WMOEssential">WMOEssential</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

```xml
<gmd:MD_DigitalTransferOptions>
  <gmd:onLine>
    <gmd:CI_OnlineResource>
      <gmd:linkage>
        <gmd:URL>https://opendata.dwd.de/weather/wmc/icon-eps/data/grib</gmd:URL>
      </gmd:linkage>
      <gmd:protocol>
        <gco:CharacterString>http</gco:CharacterString>
      </gmd:protocol>
      <gmd:name>
        <gco:CharacterString>GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:name>
      <gmd:description>
        <gco:CharacterString>WMO Information System, download products/data through GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:description>
    </gmd:CI_OnlineResource>
  </gmd:onLine>
</gmd:MD_DigitalTransferOptions>
```

==== WMO Guidelines

If the data described is categorized as `WMOEssential`, provide a link to the data.

=== XPaths

* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints`
* `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage`
