== KPI-5: WMOEssential data links

=== Measurement

Check that distribution URLs are included when the 'WMO_DataLicenseCode' 
of 'WMOEssential' is indicated in the resource constraint section.

=== Rationale for measurement

Products that qualify as WMOEssential should be available with "free and unrestricted international exchange", and therefore, should have at least one distribution link present in the metadata.

=== Rules

.WMOEssential data links implementation rules
|===
|Rule |Score

a|1..n distribution links are present when `WMO_DataLicenseCode` is `WMOEssential`. 
|1

|===

*Total possible score: 1 (100%)*

=== Guidance

If the data described is categorized as `WMOEssential`, provide a link to the data.

==== XML Examples

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode_WMOEssential">WMOEssential</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

```xml
<gmd:MD_DigitalTransferOptions>
  <gmd:onLine>
    <gmd:CI_OnlineResource>
      <gmd:linkage>
        <gmd:URL>https://opendata.dwd.de/weather/wmc/icon-eps/data/grib</gmd:URL>
      </gmd:linkage>
      <gmd:protocol>
        <gco:CharacterString>http</gco:CharacterString>
      </gmd:protocol>
      <gmd:name>
        <gco:CharacterString>GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:name>
      <gmd:description>
        <gco:CharacterString>WMO Information System, download products/data through GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:description>
    </gmd:CI_OnlineResource>
  </gmd:onLine>
</gmd:MD_DigitalTransferOptions>
```

==== WMO Guidelines

* 5.8.1.10 Data policy information

=== XPaths

* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints`
* `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage`
