== KPI-6: Keywords

=== Measurement

Keywords are present, grouped by type and referenced to controlled vocabularies or thesaurus. 

Note, WCMP 1.3 defines other rules for keywords that are not included in this measurement.

==== Rationale for measurement

Encouraging metadata providers to make use of keywords that are published in
controlled vocabularies will ultimately help the end user to search for
well-known domain related terms.

Keywords are indexed by search engines to narrow down full text searches,
adding to the user experience and making datasets easier to discover. Keywords
can be user-defined or specified from controlled vocabularies.

=== Rules

.Keywords implementation rules
|===
|Rule |Score

|6.1: There are one to many `keyword` elements present.
|1

a|6.2: The `MD_KeywordTypeCodeType` is present.

|1

a|6.3: The `title` element for the thesuarus name is present.
|1

a|6.4: Keywords and thesaurus names are implemented in the `Anchor` element .
|1

|===

*Total possible score: 4 per keyword set (100%)* (FIX THIS)

To assess how many keywords are present and provide a total percentage
based on the number of keywords and individual scoring.

=== Guidance

A high score will be provided for full referenced term, keyword type and
thesaurus. 

Examples of controlled vocabularies:

* https://codes.wmo.int[WMO Codes Registry]
* https://wis.wmo.int/2012/codelists/WMOCodeLists.xml[WMO Codelists]
* https://www.eionet.europa.eu/gemet/en/inspire-themes[General Multilingual Environmental Thesaurus (GEMET) - INSPIRE Spatial Data Themes]
* https://earthdata.nasa.gov/earth-observation-data/find-data/gcmd/gcmd-keywords[Global Change Master Directory (GCMD)]
* https://cfconventions.org/standard-names.html[Climate and Forecast (CF) Standard Names]
* https://canada.multites.net/cst[Government of Canada Core Subject Thesaurus (CST)]


==== WMO Guidelines

*5.8.1.8 Descriptive keywords

==== XML Examples

The `keyword` value is included in an `Anchor` element with a resolvable HTTP URL. 

```xml
  <gmd:MD_Keywords>
    <gmd:keyword>
     <gmx:Anchor 
        xlink:href="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode_meteorology">meteorology<gmx:Anchor>
    </gmd:keyword>
  </gmd:MD_Keywords>
```

The `type` of keyword is given in `MD_KeywordTypeCode` element, the "codelist" indicates URL of the code list.

```xml
<gmd:type>
  <gmd:MD_KeywordTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_KeywordTypeCode_theme" codeListValue="theme">theme</gmd:MD_KeywordTypeCode>
</gmd:type>
```

The thesaurus name is included in an `Anchor` element with a resolvable HTTP URL.

```xml
<gmd:thesaurusName>
  <gmd:CI_Citation>
    <gmd:title>
      <gmx:Anchor xlink:href="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode">WMO_CategoryCode</gmx:Anchor>
    </gmd:title>
    <gmd:date>
      <gmd:CI_Date>
        <gmd:date>
          <gco:Date>2016-05-26</gco:Date>
        </gmd:date>
        <gmd:dateType>
          <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
        </gmd:dateType>
      </gmd:CI_Date>
    </gmd:date>
  </gmd:CI_Citation>
</gmd:thesaurusName>
```

==== XPaths

* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:type`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName`
