== KPI-{counter:kpi}: Keywords

=== Status

Approved

=== WCMP element(s)

* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:type`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName`

=== What is being measured

* presence of keywords
* grouping of similar keywords
* reference to controlled vocabularies

In addition to measure well-defined references to dictionaries and keyword
types, compliance to WCMP 1.3 defines a set of rules that apply to different
sets of keywords.  

=== Rationale for measurement

Encouraging metadata providers to make use of keywords that are published in
controlled vocabularies will ultimately help the end user to search for
well-known domain related terms.

Keywords are indexed by search engines to narrow down full text searches,
adding to the user experience and making datasets easier to discover. Keywords
can be user-defined or specified from controlled vocabularies.

=== Rules for implementation

==== Well defined keywords examples

Used keyword references URL of acode registry using an Anchor element.

```xml
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gmx:Anchor xlink:href="https://codes.wmo.int/grib2/codeflag/4.2/_0-0-6">Dewpoint Temperature</gmx:Anchor>
    </gmd:keyword>
  </gmd:MD_Keywords>
```

The type of keyword is given in `MD_KeywordTypeCode` element, the "codelist" indicates URL of the code list, e.g. https://wis.wmo.int/2012/codelists/WMOCodeLists#MD_KeywordTypeCode.

```xml
<gmd:type>
  <gmd:MD_KeywordTypeCode codeList="https://wis.wmo.int/2012/codelists/WMOCodeLists#MD_KeywordTypeCode" codeListValue="dataParam">dataParam</gmd:MD_KeywordTypeCode>
</gmd:type>
```

Keywords reference a thesaurus using an Anchor element with a resolvable HTTP URL.

```xml
<gmd:thesaurusName>
  <gmd:CI_Citation>
    <gmd:title>
      <gmx:Anchor xlink:href="https://codes.wmo.int/grib2/codeflag/_4.2">WMO Codes Registry GRIB edition 2</gmx:Anchor>
    </gmd:title>
    <gmd:date>
      <gmd:CI_Date>
        <gmd:date>
          <gco:Date>2016-06-25</gco:Date>
        </gmd:date>
        <gmd:dateType>
          <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
        </gmd:dateType>
      </gmd:CI_Date>
    </gmd:date>
  </gmd:CI_Citation>
</gmd:thesaurusName>
```

Less prefered is to use a `gco:CharacterString` element. Such thesaurus references are still quite common, and formaly valid, but are considreded deprecated.

```xml
<gmd:thesaurusName>
  <gmd:CI_Citation>
    <gmd:title>
      <gco:CharacterString>WMO Codes Registry - GRIB edition 2</gco:CharacterString>
    </gmd:title>
    <gmd:date>
      <gmd:CI_Date>
        <gmd:date>
          <gco:Date>2016-06-25</gco:Date>
        </gmd:date>
        <gmd:dateType>
          <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
        </gmd:dateType>
      </gmd:CI_Date>
    </gmd:date>
  </gmd:CI_Citation>
</gmd:thesaurusName>
```

.Keywords implementation rules
|===
|Rule |Score

a|`gmd:keywords` is present
|1

a|`gmd:type` is present

|1

a|`gmd:thesaurusName` is present
|1

a| Keywords terms and thesaurus are present via `gmx:Anchor`
|1

|===

*Total possible score: 4 per keyword set (100%)*

To assess how many keywords are present and provide a total percentage
based on the number of keywords and individual scoring.

=== Guidance to score well on this assessment

A high score will be provided for full referenced term, keyword type and
thesaurus. Additional recommendations for keywords implementation are found at
the Guide to WMO Information System (WMO- No. 1061,Section 5.8.1.8).footnote:[https://library.wmo.int/index.php?lvl=notice_display&id=6856]

Examples of controlled vocabularies: 

* https://codes.wmo.int[WMO Codes Registry]
* https://wis.wmo.int/2012/codelists/WMOCodeLists.xml[WMO Codelists]
* https://www.eionet.europa.eu/gemet/en/inspire-themes[General Multilingual Environmental Thesaurus (GEMET) - INSPIRE Spatial Data Themes]
* https://earthdata.nasa.gov/earth-observation-data/find-data/gcmd/gcmd-keywords[Global Change Master Directory (GCMD)]
* https://cfconventions.org/standard-names.html[Climate and Forecast (CF) Standard Names]
* https://canada.multites.net/cst[Government of Canada Core Subject Thesaurus (CST)]

