== KPI-7: Graphic overview for non bulletins metadata records

=== Measurement

The gmd:graphicOverview element for a non-bulletin metadata record is present and it contains a URL to a common web image file type.[1]

=== Rationale for measurement

Product graphic overviews provide the user with a high level preview of the product which can assist in a high level assessment as part of search results presentation.

=== Rules

.Graphic overview for non bulletins metadata records implementation rules
|===
|Rule |Score

|The graphic overview element is present.
|1

|The graphic overview URL resolves successfully.
|1

|The URL in this element is a common web image file type
(check MIME type, content header/magic number)
|1
|===

*Total possible score: 3 (100%)*

=== Guidance

In addition to the presence of the graphic overview image it would also be
valuable to provide consistent image dimensions (e.g. 800x800 pixels) such that
all images are normalized and scaling/alignment of overivew images can be
applied consistently by web applications rendering search results.

Examples of catalogues using such information are here:

* https://gisc.dwd.de[GISC DWD]
* https://navigator.eumetsat.int/search?query=MSG%20RGB[EUMETSAT Product Navigator]

==== XML Examples

```xml
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
     <gmd:fileName>
        <gmx:Anchor 
         xlink:href="https://navigator.eumetsat.int/preview/meteosat-msg_naturalenhncd.jpg">Meteosat MSG Natural Enhanced Color<gmx:Anchor>
     </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

==== WMO Guidelines

* 5.8.1.9	Product sample visualization URL

=== XPaths

* `//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:fileName/gmx:Anchor/@xlink:href`
