== KPI-{counter:kpi}: Graphic overview for non bulletins metadata records

=== WCMP element(s)

* `//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:filename/gmx:Anchor/@xlink:href`

```xml
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
     <gmd:fileName>
        <gmx:Anchor xlink:href="https://navigator.eumetsat.int/preview/meteosat-msg_naturalenhncd.jpg">Meteosat MSG Natural Enhanced Color</gmx:Anchor>
     </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

=== What is being measured

The presence of `gmd:graphicOverview` is checked that it contains a URL to
a common web image file type.footnote:[https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#Common_image_file_types].

=== Rationale for measurement

Product graphic overviews provide the user with a high level preview of the
product which can assist in a high level assessment and/or evaluation as part
of search results presentation.

=== Rules for implementation

.Graphic overview for non bulletins metadata records implementation rules
|===
|Rule |Score

|graphic overview element exists
|1

|graphic overview URL resolves successfully
|1

|graphic overview URL content is a common web image file type
(check MIME type, content header/magic number)
|1
|===

*Total possible score: 3 (100%)*

=== Guidance to score well on this assessment

In addition to the presence of the graphic overview image it would also be
valuable to provide consistent image dimensions (e.g. 800x800 pixels) such that
all images are normalized and scaling/alignment of overivew images can be
applied consistently by web applications rendering search results.

Examples of catalogues using such information are here:

* https://gisc.dwd.de[GISC DWD]
* https://navigator.eumetsat.int/search?query=MSG%20RGB[EUMETSAT Product Navigator]

