== KPI-8: Links health

=== Measurement

Links are valid (no 4xx or 5xx HTTP status errors) and are available through the HTTPS protocol. 

=== Rationale for measurement

Broken links damage the user experience and gives the impression to users that
a website is not maintained. 

HTTPS is increasingly becoming a requirement for numerous agencies.  Metadata records with non-HTTPS links often leads to mixed
content errors in web applications deployed via HTTPS. HTTPS supports secure, authoritative and trustworthy links as part of WIS metadata.

=== Rules
|===
| |Rule |Score

|8.1| The link resolves, when it is present in `gmd:URL` element, `gmd:fileName` element, `xlink:href` attribute, or `codeList` attribute. 
|1
|8.2| Each link is a valid HTTPS URL.
|1
|===

*Total possible score: (resolved links + valid HTTPS links) / (total links * 2) (100%)*

=== Guidance

Ensure that all links are up to date in the metadata and are accessible via HTTPS. Don't put URLs in the abstract or other elements that are intended for free text. 

For more information about HTTP status errors, visit https://httpstatuses.com.

==== XML Examples

```xml
<gmd:CI_OnlineResource>
 <gmd:linkage>
   <gmd:URL>https://eumetview.eumetsat.int/mapviewer/?product=EO:EUM:DAT:MSG:SNOW</gmd:URL>
 </gmd:linkage>
</gmd:CI_OnlineResource>
```

```xml
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
    <gmd:fileName>
      <gco:CharacterString>https://navigator.eumetsat.int/preview/0deg-snow.jpg</gco:CharacterString>
    </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

```xml
<gmd:code>
  <gmx:Anchor xlink:actuate="onRequest" xlink:href="https://dx.doi.org/10.14287/10000004" xlink:title="DOI">doi:10.14287/10000004</gmx:Anchor>
</gmd:code>
```

```xml
<gmd:dateType>
  <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision" codeSpace="ISOTC211/19115">revision</gmd:CI_DateTypeCode>
</gmd:dateType>
```

==== XPaths

* `//gmd:URL`
* `//gmd:graphicOverview//gmd:fileName`
* `//gmx:Anchor/@xlink:href`
* `//@codeList`

