== KPI-9: Data policy and exchange

=== Measurement
This KPI extends ATS requirements 9.1.1, 9.3.1 and 9.3.2 for all types of data, not just data that are for global exchange. 

Distribution URLs are present when the `WMO_DataLicenseCode` code value is `WMOEssential`, keyword section is complete for `WMO_DistributionScopeCode` values and codes are encoded with `gmx:Anchor` elements for resource constraints and keywords. 

=== Rationale for measurement

=== Rules
|===

| |Rule |Score

| 9.1 | "WMO_DistributionScopeCode" is present in the "gmd:keyword" element and it is associated with the value of “WMO_DistributionScopeCode” in "gmd:thesaurusName//gmd:title" element and “dataCentre” or “dataCenter” in the "gmd:MD_KeywordTypeCode" element. | 1

| 9.2 | "WMO_DataLicenseCode" is present in the "gmd:otherConstraints" element in the "gmd:MD_LegalConstraints" class. |1

| 9.3 | The "WMO_GTSProductCategoryCode" is present in the "gmd:otherConstraints" element when the value of “WMO_DistributionScopeCode” is `GlobalExchange` or `RegionalExchange`.|1

| 9.4 |One to many distribution links are present when `WMO_DataLicenseCode` is `WMOEssential`. 
|1

| 9.5 | The code value `otherRestrictions` is present in both the `gmd:accessConstraints` and `gmd:useContraints` elements in the `gmd:MD_LegalConstraints` class where the `WMO_DataLicenseCode` and/or `WMO_GTSProductCategoryCode` are present. 
| 1

| 9.6 |The `WMO_DataLicenseCode`, `WMO_GTSProductCategoryCode`, `WMO_DistributionScopeCode`, `WMO_DistributionScopeCode` code values are implemented in the `gmx:Anchor` element, instead of the `gco:CharacterString` element.
|1

|===

*Total possible score: 6 (100%)*

=== Guidance
Requirement 9.1.1 tests for the existence of 'GlobalExchange', but WMO_DistributionScopeCode should be used to describe any type of metadata record in WIS. To score well in KPI 9.1 use "OriginatingCenter" for all data not published with 'GlobalExchange' or 'RegionalExhange' codes.

To score well on KPI 9.2, always include a "WMO_DataLicenseCode" for all types of data. If the license is unknown, then use "WMOOther" code.

Additional descriptions to explain the referred `WMO_DataLicenseCode` could be added in additional `gmd:otherRestrictions` elements.

There can be free text explanations in additional `gmd:otherConstraints` or `gmd:useLimitation` elements.

Summary of elements evaluated in the `gmd:MD_LegalConstraints` class. 

[%header,cols=2*]
|===
|Element
|Description

a|`gmd:accessConstraints`
a|`gmd:MD_RestrictionCode` = `otherRestrictions`

a|`gmd:useConstraints`
a|`gmd:MD_RestrictionCode` = `otherRestrictions`

a|`gmd:otherConstraints`
a|Vocabulary controlled: `WMO_DataLicenseCode` (`WMOEssential`, `WMOAdditional`, `WMOther`, `NoLimitation`)

a|`gmd:otherConstraints`
a|Vocabulary controlled: `WMO_GTSProductCategoryCode` (`GTSPriority1`, `GTSPriority2`, `GTSPriority3`, `GTSPriority4`)

|===

==== References

* Manual on WIS 
** Abstract Test Suite 
** Appendix C, 9.2	Identifiers for metadata describing data published for global exchange
** Appendix C, 9.3	Defining WMO data policy and GTS priority for data published for global exchange
* Guide to WIS
** 5.8.1.10	Data policy information

==== XML Examples
Example of `gmd:MD_LegalConstraints` section.

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
     <gmd:accessConstraints>
         <gmd:MD_RestrictionCode
            codeList=”https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_RestrictionCode”
            codeListValue=”otherRestrictions”>
            otherRestrictions
     </gmd:MD_RestrictionCode>
  </gmd:accessConstraints>
  <gmd:useConstraints>
     <gmd:MD_RestrictionCode
            codeList=”https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_RestrictionCode”
            codeListValue=”otherRestrictions”>
            otherRestrictions
     </gmd:MD_RestrictionCode>
  </gmd:useConstraints>
  <gmd:otherConstraints>
    <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode">WMOEssential</gmx:Anchor>
  </gmd:otherConstraints>
  <gmd:otherConstraints>
    <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_GTSProductCategoryCode">GTSPriority3</gmx:Anchor>
     </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

=== XPaths
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:type`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName`
* `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints/gmd:MD_RestrictionCode`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints/gmd:MD_RestrictionCode`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints`


