== KPI-9: Data policy

=== Measurement
Codes list values to represent the applicable WMO data policies are present and encoded correctly in resource constraints and keyword sections. 

=== Rationale for measurement

Data policy provides information to the users about how the data should be handled and  
the conditions of use for the resource published should be clear to the user.
Data providers also have the obligation to define the scope of the distribution of
the data within WIS and, when applicable, the GTS priority. 

=== Rules

.Data policy implementation rules
|===
|Rule |Score

|9.1: A `WMO_DataLicenseCode` value is present in the `gmd:otherConstraints` element of the `gmd:MD_LegalConstraints` section.
|1

|9.2: The code value `otherRestrictions` is present in the `gmd:MD_RestrictionCode` element of the`gmd:accessConstraints`and`gmd:useConstraints`sections. 
|1

|9.3: A `WMO_DistributionScopeCode` value is present in a `gmd:keywords` element, the code value `dataCentre` is present in the associated `gmd:MD_KeywordTypeCode` element and `WMO_DistributionScopeCode` is present in the  `gmd:title` element for a the thesaurus name. 
|1

|9.4: A `WMO_GTSProductCategoryCode` value is present in the `gmd:otherConstraints` element of the `gmd:MD_LegalConstraints` section when the `WMO_DistributionScopeCode` value described in 9.3 is `GlobalExchange` or `RegionalExchange`.
|1

|9.5: The `WMO_DataLicenseCode` (in `gmd:otherConstraints`), `WMO_GTSProductCategoryCode` (in `gmd:otherConstraints`), 
`WMO_DistributionScopeCode` (in `gmd:keywords`), `WMO_DistributionScopeCode` (in Thesaurus title) are implemented in the Anchor element, instead of the CharacterString element.
|1
|===

*Total possible score: 5 (100%)*

Note: Other possible `gmd:resourceConstraints` elements may exist and not comply to these rules.
The score checks that there is at least one `gmd:resourceConstraints` section that complies to
the rules.

=== Guidance

If the codelist implementation is not clear enough there can be additional free text explanations in the `gmd:useLimitation` element or in addition `gmd:otherConstraints` elements. 

==== WMO Guidelines

* Manual on WIS: Appendix C, 9.3	Defining WMO data policy and GTS priority for data published for global exchange
* Guide to WIS: 5.8.1.10	Data policy information

==== XML Examples

Example for a code value that is implemented with the `gmx:Anchor` element, instead of the `gco:CharacterString` element. 

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode_WMOAdditional">WMOAdditional</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```
Example for `gmd:otherRestrictions` code value. 

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:useConstraints>
      <gmd:MD_RestrictionCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
    </gmd:useConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

Example of keyword section with `WMO_DistributionScopeCode` and `gmd:KeywordTypeCode` = `dataCentre`.

```xml
<gmd:MD_Keywords>
  <gmd:keyword>
    <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DistributionScopeCode_GlobalExchange">GlobalExchange</gmx:Anchor>
  </gmd:keyword>
  <gmd:type>
    <gmd:MD_KeywordTypeCode codeList="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_KeywordTypeCode" codeListValue="dataCenter">dataCenter</gmd:MD_KeywordTypeCode>
  </gmd:type>
  <gmd:thesaurusName>
    <gmd:CI_Citation>
      <gmd:title>
        <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DistributionScopeCode">WMO_DistributionScopeCode</gmx:Anchor>
      </gmd:title>
      <gmd:date>
        <gmd:CI_Date>
          <gmd:date>
            <gco:Date>2012-06-27</gco:Date>
          </gmd:date>
          <gmd:dateType>
            <gmd:CI_DateTypeCode codeList="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
          </gmd:dateType>
        </gmd:CI_Date>
      </gmd:date>
    </gmd:CI_Citation>
  </gmd:thesaurusName>
</gmd:MD_Keywords>
```

Example of `WMO_GTSProductCategoryCode` in `gmd:resourceConstraints` section. 

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
   <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_GTSProductCategoryCode_GTSPriority3">GTSPriority3</gmx:Anchor>
   </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

=== XPaths

* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints/gmd:MD_RestrictionCode`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints/gmd:MD_RestrictionCode`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:type`
* `//gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName`
