== KPI-9: Data policy

=== Measurement

Distribution URLs are present when the `WMO_DataLicenseCode` code value is  `WMOEssential`. 

##Codes list values to represent the applicable WMO data policies are present and encoded correctly in resource constraints and keyword class. 

=== Rationale for measurement

KPI-1 evaluates the the record for compliance with Abstract Test Suite requirements 9.1.1, 9.3.1 and 9.3.2. This KPI evaluates additional practices that support information associated with the identification of the these data policies.

In addition, products that qualify as available with "free and unrestricted international exchange", which is identified by the  `WMOEssential` code, should have at least one distribution link present in the metadata.


##Requirement 9.1.1: A WIS discovery metadata record describing data for global exchange via the WIS shall indicate the scope of distribution using the keyword “GlobalExchange” of type “dataCentre” from thesaurus WMO_DistributionScopeCode.

##Requirement 9.3.1: A WIS discovery metadata record describing data for global exchange via the WIS shall indicate the WMO data license as legal constraint (type: “otherConstraints”) using one and only one term from the WMO_DataLicenseCode code list.

##Requirement 9.3.2: A WIS discovery metadata record describing data for global exchange via the WIS shall indicate the GTS priority as legal constraint (type: “otherConstraints”) using one and only one term from the WMO_GTSProductCategoryCode code list.

=== Rules

.Data policy implementation rules
|===

|Rule |Score

|One to many distribution links are present when `WMO_DataLicenseCode` is `WMOEssential`. 
|1

|The code value `otherRestrictions` is present in the `gmd:MD_RestrictionCode` element of the`gmd:MD_LegalConstraints` class when there is a `WMO_DataLicenseCode` or `WMO_GTSProductCategoryCode` in the `gmd:otherConstraints` element. 
|1

|The `WMO_DataLicenseCode`, `WMO_GTSProductCategoryCode`, `WMO_DistributionScopeCode`, `WMO_DistributionScopeCode` code values are implemented in the `gmx:Anchor` element, instead of the `gco:CharacterString` element.
|1

|===

*Total possible score: 3 (100%)*

=== Guidance
The KPI checks that there is at least one `gmd:resourceConstraints` class that complies to
the rules and other `gmd:resourceConstraints` classes may exist. For example, additional free text explanations can be added to a `gmd:useLimitation` element or in additional `gmd:MD_LegalConstraint` classes.

==== WMO Guidelines

* Manual on WIS 
** Appendix C, 9.3	Defining WMO data policy and GTS priority for data published for global exchange
** Abstract Test Suite 
* Guide to WIS: 5.8.1.10	Data policy information

==== XML Examples

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode_WMOEssential">WMOEssential</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

```xml
<gmd:MD_DigitalTransferOptions>
  <gmd:onLine>
    <gmd:CI_OnlineResource>
      <gmd:linkage>
        <gmd:URL>https://opendata.dwd.de/weather/wmc/icon-eps/data/grib</gmd:URL>
      </gmd:linkage>
      <gmd:protocol>
        <gco:CharacterString>http</gco:CharacterString>
      </gmd:protocol>
      <gmd:name>
        <gco:CharacterString>GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:name>
      <gmd:description>
        <gco:CharacterString>WMO Information System, download products/data through GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:description>
    </gmd:CI_OnlineResource>
  </gmd:onLine>
</gmd:MD_DigitalTransferOptions>
```



Example for a code value that is implemented with the `gmx:Anchor` element, instead of the `gco:CharacterString` element. 

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DataLicenseCode_WMOAdditional">WMOAdditional</gmx:Anchor>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```
Example for `gmd:otherRestrictions` code value. 

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:useConstraints>
      <gmd:MD_RestrictionCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
    </gmd:useConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

Example of keyword class with `WMO_DistributionScopeCode` and `gmd:KeywordTypeCode` = `dataCentre`.

```xml
<gmd:MD_Keywords>
  <gmd:keyword>
    <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DistributionScopeCode_GlobalExchange">GlobalExchange</gmx:Anchor>
  </gmd:keyword>
  <gmd:type>
    <gmd:MD_KeywordTypeCode codeList="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_KeywordTypeCode" codeListValue="dataCenter">dataCenter</gmd:MD_KeywordTypeCode>
  </gmd:type>
  <gmd:thesaurusName>
    <gmd:CI_Citation>
      <gmd:title>
        <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_DistributionScopeCode">WMO_DistributionScopeCode</gmx:Anchor>
      </gmd:title>
      <gmd:date>
        <gmd:CI_Date>
          <gmd:date>
            <gco:Date>2012-06-27</gco:Date>
          </gmd:date>
          <gmd:dateType>
            <gmd:CI_DateTypeCode codeList="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
          </gmd:dateType>
        </gmd:CI_Date>
      </gmd:date>
    </gmd:CI_Citation>
  </gmd:thesaurusName>
</gmd:MD_Keywords>
```

Example of `WMO_GTSProductCategoryCode` in `gmd:resourceConstraints` class. 

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
   <gmd:otherConstraints>
      <gmx:Anchor xlink:href="https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_GTSProductCategoryCode_GTSPriority3">GTSPriority3</gmx:Anchor>
   </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```

=== XPaths
* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints`
* `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:otherConstraints`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:accessConstraints/gmd:MD_RestrictionCode`
* `//gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useConstraints/gmd:MD_RestrictionCode`