== KPI-10: Distribution information

=== Measurement

Distribution information for accessing the data, 
data formats, and contact details are present.

=== Rationale for measurement

Distribution information allows the user to understand what formats are available, where to get it and who to contact for distribution details. 

=== Rules

.Distribution information implementation rules
[cols="1a,2"]
|===
|Rule |Score

|10.1: The `gmd:MD_Format` section is present.
|1

|10.2: The `gmd:specification` element in the `gmd:MD_Format` section has an `gmx:Anchor` with a resolvable HTTP URL.
|1

|10.3: The `gmd:organisationName` element in the `gmd:MD_Distributor` section is present. 
|1

|10.4: The `gmd:electronicMailAddress` in the `gmd:MD_Distributor` section is present. 
|1

|10.5: One to many `gmd:MD_DigitalTransferOptions` options are present. 
 |1

|===

*Total possible score: 5 (100%)*

=== Guidance

* Include the relevant WMO data formats in the `gmd:MD_Format` sections with a link to the specification of the data format. 
* Include all relevant URLs in the `gmd:MD_DigitalTransferOptions` section for accessing the data.  
* A distributor contact does not have to be the same as the other contacts in the metadata and should always have a contact email.  

==== WMO References
* 5.8.1.11	Distribution information

==== XML Examples
```xml
<gmd:distributionInfo>
  <gmd:MD_Distribution>
    <gmd:distributionFormat>
      <gmd:MD_Format>
        <gmd:name>
          <gco:CharacterString>FM 94 (BUFR)</gco:CharacterString>
        </gmd:name>
        <gmd:version>
          <gco:CharacterString>XII EXT.</gco:CharacterString>
        </gmd:version>
        <gmd:specification>
          <gmx:Anchor xlink:title="FM 94 (BUFR)" xlink:href="https://www.wmo.int/pages/prog/www/WMOCodes.html">FM 94 (BUFR)</gmx:Anchor>
        </gmd:specification>
      </gmd:MD_Format>
    </gmd:distributionFormat>
    <gmd:distributor>
      <gmd:MD_Distributor>
        <gmd:distributorContact>
          <gmd:CI_ResponsibleParty>
            <gmd:organisationName>
              <gco:CharacterString>NMC FRANCE - Météo-France</gco:CharacterString>
            </gmd:organisationName>
            <gmd:contactInfo>
              <gmd:CI_Contact>
                <gmd:phone/>
                <gmd:address>
                  <gmd:CI_Address>
                    <gmd:deliveryPoint>
                      <gco:CharacterString>Direction des Systèmes d'Information, 42 avenue Gaspard CORIOLIS</gco:CharacterString>
                    </gmd:deliveryPoint>
                    <gmd:city>
                      <gco:CharacterString>TOULOUSE</gco:CharacterString>
                    </gmd:city>
                    <gmd:postalCode>
                      <gco:CharacterString>31057</gco:CharacterString>
                    </gmd:postalCode>
                    <gmd:country>
                      <gco:CharacterString>France</gco:CharacterString>
                    </gmd:country>
                    <gmd:electronicMailAddress>
                      <gco:CharacterString>gisc_support@meteo.fr</gco:CharacterString>
                    </gmd:electronicMailAddress>
                  </gmd:CI_Address>
                </gmd:address>
                <gmd:onlineResource>
                  <gmd:CI_OnlineResource>
                    <gmd:linkage>
                      <gmd:URL>https://meteofrance.com</gmd:URL>
                    </gmd:linkage>
                  </gmd:CI_OnlineResource>
                </gmd:onlineResource>
              </gmd:CI_Contact>
            </gmd:contactInfo>
            <gmd:role>
              <gmd:CI_RoleCode codeListValue="pointOfContact" codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode">pointOfContact</gmd:CI_RoleCode>
            </gmd:role>
          </gmd:CI_ResponsibleParty>
        </gmd:distributorContact>
      </gmd:MD_Distributor>
    </gmd:distributor>
    <gmd:transferOptions>
      <gmd:MD_DigitalTransferOptions>
        <gmd:onLine>
          <gmd:CI_OnlineResource>
            <gmd:linkage>
              <gmd:URL>http://wispi.meteo.fr/openwis-user-portal/srv/en/main.home?urn=urn:x-wmo:md:int.wmo.wis::ISMN10LFPW</gmd:URL>
            </gmd:linkage>
            <gmd:protocol>
              <gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString>
            </gmd:protocol>
            <gmd:name>
              <gco:CharacterString>Permanent link</gco:CharacterString>
            </gmd:name>
            <gmd:description>
              <gco:CharacterString>GISC Toulouse</gco:CharacterString>
            </gmd:description>
          </gmd:CI_OnlineResource>
        </gmd:onLine>
      </gmd:MD_DigitalTransferOptions>
    </gmd:transferOptions>
  </gmd:MD_Distribution>
</gmd:distributionInfo>
```

=== XPaths

* `//gmd:distributionInfo//gmd:distributionFormat/gmd:MD_Format`
* `//gmd:distributionInfo//gmd:MD_DigitalTransferOptions//gmd:onLine//gmd:URL`
* `//gmd:distributionInfo//gmd:MD_Distributor//gmd:organisationName`
* `//gmd:distributionInfo//gmd:MD_Distributor//gmd:contactInfo//gmd:electronicMailAddress/gco:CharacterString`

