== KPI-11: Codelists validation

=== Measurement

Each code value in the metadata is an exact match to the code in one of the authoritative codelists below.

* ISO Codelists: https://standards.iso.org/iso/19139/resources/gmxCodelists.xml
* WMO Codelists/ISO extensions: https://wis.wmo.int/2012/codelists/WMOCodeLists.xml

==== Rationale for measurement

WCMP records can reference codelists from several locations, for example, online copies of the authoritative sources.
In many cases codes are included but are not identical to the official values
on the codelists (e.g. spelling mistakes, case sensitivity errors, etc.). Software applications may look for exact matches to codelists and handle metadata incorrectly if they are not properly referenced.

=== Rules
|===
| |Rule |Score

|11.1| Code value is valid against authoritative codelists with an exact match.
|1

|===

*Total possible score: valid codes / total codes (100%)*

=== Guidance

An exact match means that there are no differences with spacing or capitalization. For example, 
`Other restrictions` and `other_restrictions` will not validate. Only the code value `otherRestrictions` from the `MD_RestrictionCode` codelist will validate. 

==== XPaths

[%header,cols=3*]
|===
|Codelist
|XPath
|Authoritative list

a|`CI_DateTypeCode`
a|`//gmd:date/gmd:CI_Date/gmd:dateType/gmd:CI_DateTypeCode`
| WMOCodeLists (ISO Extended)

a|`CI_RoleCode`
a|`//gmd:CI_ResponsibleParty/gmd:role/gmd:CI_RoleCode`
|gmxCodelists (ISO)

a|`MD_KeywordTypeCode`
a|`//gmd:MD_Keywords/gmd:type/gmd:MD_KeywordTypeCode`
|WMOCodeLists (ISO Extended)

a|`MD_RestrictionCode`
a|`//gmd:resourceConstraints//gmd:MD_RestrictionCode`
|gmxCodelists (ISO)

a|`MD_ScopeCode`
a|`//gmd:scope//gmd:MD_ScopeCode`
|gmxCodelists (ISO)

a|`MD_TopicCategoryCode`
a|`//gmd:topicCategory/gmd:MD_TopicCategoryCode`
|gmxCodelists (ISO)

a|`WMO_DataLicenseCode`
a|`//gmd:resourceConstraints//gmd:otherConstraints/[gco:CharacterString\|gmx:Anchor]`
|WMOCodeLists

a|`WMO_GTSProductCategoryCode`
a|`//gmd:resourceConstraints//gmd:otherConstraints/[gco:CharacterString\|gmx:Anchor]`
|WMOCodeLists

a|`WMO_CategoryCode`
a|`//gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword/[gco:CharacterString\|gmx:Anchor]`
|WMOCodeLists

a|`WMO_DistributionScopeCode`
a|`//gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:keyword/[gco:CharacterString\|gmx:Anchor]`
|WMOCodeLists

|===

