== A. Compliance to WMO Core Profile and its mandatory elements
////
They should be derived from WMCP documentation part 2 and the rubric
checker. To be done
////


=== A.1) XML encoding : ISO/TS 19139:2007 Compliance

==== To which WMCP element(s) does it apply?
Whole metadata record

==== What is being measured?
Metadata record structure conforms to that defined in ISO/TS 19139:2007 standard

==== Why should we measure it?
A WCMP Metadata record shall validate without error against the XML schema defined in  ISO/TS 19139:2007.  A invalid metadata record will be rejected by the WIS DAR catalog, so related datasets won’t be discoverables and accessibles.

==== How is the measurement executed?
Tools recommended in WCMP ATS, like rubric checker.

==== What is (are) considered valid results?
No error in checker output

==== Guidance to score well on this assessment
validate the metadata record  using rubric checker before publishing it


=== A.2) XML encoding : Explicit namespace identification 

==== To which WMCP element(s) does it apply?
Whole metadata record

==== What is being measured?
Each element is prefixed with it’s namespace prefix  (ie : gmd gmx, ...)

==== Why should we measure it?
To avoid collisions among elements from different packages in a metadata record 

==== How is the measurement executed?

==== What is (are) considered valid results?

==== Guidance to score well on this assessment


=== A.3) XML encoding : Use of GML 3.2

==== To which WMCP element(s) does it apply?
Whole metadata record, namespace declaration 

==== What is being measured?

==== Why should we measure it?
Wcmp 1.3 depends on gml 3.2.  A metadata record using another gml version may be rejected by the WIS DAR catalog.

==== How is the measurement executed?
Tools recommended in WCMP ATS, like rubric checker 

==== What is (are) considered valid results?

==== Guidance to score well on this assessment


=== A.4) Uniqueness of metadata record : Presence of the FileIdentifier element 

==== To which WMCP element(s) does it apply?
gmd:MD_Metadata/gmd:fileIdentifier

==== What is being measured?
Presence of gmd:FileIdentifier element in the metadata record.
The gmd:FileIdentifier value is an URI compliant with the specified stucture in WCMP Part 1

==== Why should we measure it?
To ensure uniqueness of the metadata record within the WIS.

==== How is the measurement executed?
Tools recommended in WCMP ATS, like rubric checker 

==== What is (are) considered valid results?
No error related to the presence of  gmd:FileIdentifier in rubric output

==== Guidance to score well on this assessment
validate the metadata record  using rubric checker before publishing it. ( Does rubric check URL compliance ? )


=== A.5) Discovery rules within the DAR catalogue : Presence of the mandatory WMO_CategoryCode keyword 

==== To which WMCP element(s) does it apply?
gmd:MD_Metadata/gmd:identificationInfo/gmd:DataIndentification/gmd:descriptiveKeywords/gmd:Keywords/gmd:keyword

==== What is being measured?
Presence and value of a keyword from the WMO_CategoryCode code list.

==== Why should we measure it?
Provide additional topic categories for data discovery in WMO community

==== How is the measurement executed?
Tools recommended in WCMP ATS, like rubric checker 

==== What is (are) considered valid results?
No error related to gmd:topicCategory in checker’s output, there is at least one keyword from  WMO_CategoryCode code list in the matadata record.

==== Guidance to score well on this assessment
validate the metadata record using rubric checker before publishing it


=== A.6) Discovery rules within the DAR catalogue : Presence of the MD_TopicCategoryCode element

==== To which WMCP element(s) does it apply?
gmd:MD_Metadata/gmd:identificationInfo/gmd:DataIndentification/gmd:topicCategory

==== What is being measured?
Presence and value of the gmd:topicCategory element

==== Why should we measure it?
Provide the main theme of the dataset for data discovery

==== How is the measurement executed?
Tools recommended in WCMP ATS, like rubric checker 

==== What is (are) considered valid results?
No error related to gmd:topicCategoryCode in checker’s output

==== Guidance to score well on this assessment
validate the metadata record using rubric checker before publishing it



=== A.6) Discovery rules within the DAR catalogue : Presence of geographic data extent defined by a bounding box

==== To which WMCP element(s) does it apply?
gmd:MD_Metadata/gmd:identificationInfo/gmd:DataIndentification/gmd:extent/gmd:EX_Extent/gmd:geographicElement/gmd:EX_GeographicBoundingBox

==== What is being measured?
Presence of gmd:EX_GeographicBoundingBox

==== Why should we measure it?
Provide the geographic extent of the dataset for data discovery 

==== How is the measurement executed?
Tools recommended in WCMP ATS, like rubric checker 

==== What is (are) considered valid results?
No error related to EX_GeographicBoundingBox in checker’s output

==== Guidance to score well on this assessment
validate the metadata record using rubric checker before publishing it



=== A.7) Correct description of data for global exchange via WIS : Identifying data for global exchange

==== To which WMCP element(s) does it apply?

==== What is being measured?

==== Why should we measure it?

==== How is the measurement executed?

==== What is (are) considered valid results?

==== Guidance to score well on this assessment

=== Correct description of data for global exchange via WIS : Specification of WMO data policy for globally exchanged data

==== To which WMCP element(s) does it apply?

==== What is being measured?

==== Why should we measure it?

==== How is the measurement executed?

==== What is (are) considered valid results?

==== Guidance to score well on this assessment


=== A.8) Correct description of data for global exchange via WIS : Specification of GTS priority for globally exchanged data

==== To which WMCP element(s) does it apply?

==== What is being measured?

==== Why should we measure it?

==== How is the measurement executed?

==== What is (are) considered valid results?

==== Guidance to score well on this assessment
