== B. Good quality title

=== WMCP element(s)

`/gmd:MD_Metadata/gmd:identificationInfo//gmd:citation/gmd:CI_Citation/gmd:title`

=== What is being measured

The title field shall always be populated and and follow the principles of
WMCP guidance. The length shall not be too short or too long, contain less
than 3 acronyms and represented in title case.

=== Rationale for measurement

Title is the first element of metadata information displayed and helps with
initial identification. Meaningful and relevant information makes it easier
for users to understand the resource.

=== Rules for implementation

.Good quality title implementation rules
|===
|Rule |Score

a|title is missing:

* `<gmd:title/>`
* `<gmd:title></gmd:title>`
* `<gmd:title gco:nilReason="missing"/>`

|0

|title has 3 words or more
|1

|title has 150 characters or less
|1

|title only has printable characters (numbers and letters)
|1

|words in title are represented in "Title Case"
|1

|title contains less than 3 acronyms (words with all upper case)
|1

|title contains bulletin header (regular expression `[A-Z]{4}\d{2}[\s_]*[A-Z]{4}`)
|-1
|===

Total possible score: 5 (100%)


=== Guidance to score well on this assessment

In the context of WIS Product catalogues, the product title and abstract are
the two most relevant elements in the WCMP metadata record.  These two elements
are presented to the users in search results as well as the product description
page, and need to focus on highlighting the product’s key characteristics to
assist users with relevant product search results.

The title should be as specific about the product as possible. For example, if
the product only contains one parameter, this can be stated in the title;
however, if the product contains numerous parameters, then a more general term
should be used in the title, and the parameters stated elsewhere in the
metadata record (abstract, keywords, etc.).

For a satellite product offering one main data parameter, the title will
typically define which parameter is contained in the product, and from which
instrument or instrument type it originates. For example, "AMSR-2 Sea Surface
Temperature” or “SLSTR L1B radiances and brightness temperatures”.footnote:[WMCP Guidance (http://wis.wmo.int/file=3291)]

