== C. Good quality abstract

=== To which WCMP element(s) does it apply?
/gmd:MD_Metadata/gmd:identificationInfo//gmd:abstract

=== What is being measured?
Programmatic measurements:
* length is at least 2 or 3 sentences 
* NO URLs are included
* Spelling and grammar

Manual measurements: 
* Tone
* Completeness
* Relevancy to the resource
* Acronyms are spelled out, when applicable

=== Why should we measure it?
To faciliate ease of understanding and discovery. 

=== How is the measurement executed?
Programmatically and manually.

=== What is (are) considered valid results?
Abstract is at least 3(?) sentences, does not contain URLs, spelling and grammar are correct.

=== Guidance to score well on this assessment
*WCMP v1.3 part 1 Guidance*
The abstract should provide a clear and concise statement that enables the reader to
understand the content of the dataset. For guidance when completing the abstract, consider
these points:
(a) State what the “things” are that are recorded.
(b) State the key aspects recorded about these things.
(c) State what form the data takes.
(d) State any other limiting information, such as time period of validity of the data.
(e) Add purpose of data resource where relevant (e.g. for survey data).
(f) Aim to be understood by non-experts.
(g) Do not include general background information.
(h) Avoid jargon and unexplained abbreviations.

*NOAA Recommendation*
Brief narrative summary of the resource. This is different than a scientific abstract. Limit information in the abstract to the specific resource that is being described. Provide descriptive information in a clear, concise and human readable manner. Describe the contents of the resource and the key aspects and/or attributes that are represented. Briefly explain what is unique about this resource and, if appropriate how it differs from similar resources. Ensure contextual information important to the use of the resource are explained, e.g. formats, recommended tools, related resources, or limitations. Avoid citing external sources to this resource.
# Write using plain language that the general public will understand. Terminology that is intended for a designated community is acceptable. However, avoid overly scientific and/or technical jargon.
# Acronyms do not need to be spelled out if they are for commonly used terms which are understood by the general public. Once an uncommon acronym is spelled out within the Abstract it can be used without explanation.
# Do not include URLs. URLs change often and link checkers generally only check links in <onlineResource> portions of the metadata.
# Do not include html, csv, tables or extra spaces to control display of text. Use simple paragraph(s) only.
# Do not copy text from a journal article verbatim. This can lead to copyright violation concerns. Additionally, abstracts for journal articles are not intended to describe the provided resource and do not meet the metadata requirements. Related papers can be referenced from and/or tied to the metadata. See EDM Wiki about MD_AggregateInformation section for more information on citing journals.
# Do not include persistent identifier(s) related to this resource, e.g. DOI, referenced journals, etc. See information about including identifiers in other locations of the standard, i.e., MD_Identifier, MD_AggregateInformation, and CI_Citation Statement.
# Avoid using future verb tense when possible. Write using present or past tenses.


------

Well know bad templates for abstract should be flagged to be gradually
replaced. For instance the automatically generated bulletin records
should be replaced by records having a valid description. This can be
easily detected automatically and referenced. EDX01 BUFR bulletin
available from EUMP (EUMETSAT - DARMSTADT) Satellite Centre EUMETSAT
Darmstadt - EUMETSAT - The bulletin is coded as BUFR code form: FM 94
(BUFR, Binary universal form for the >representation of meteorological
data) . (Refer to WMO No.306 - Manual on Codes for the >definition of
WMO international codes) - The IEDX01 TTAAii Data Designators decode (2)
as: T1 >(I): Observational data (Binary coded) - BUFR. A2 (X): Global
Area (area not definable). (2: Refer to >WMO No.386 - Manual on the GTS
- Attachment II.5) - WMO No.9 - Volume C1 `Remarks' field: >IASI
SOUNDING (TEMP AND HUMIDITY) GLOBAL DATA`
