== D. Valid station identifier

A station identifier, when provided as a keyword, should be a valid WIGOS
station identifier.footnote:[https://oscar.wmo.int/surface/index.html#/search/station/stationReportDetails/0-20008-0-THE].

=== WMCP element(s)

* `//gmd:identificationInfo/gmd:descriptiveKeywords//gmd:thesaurusName/@xlink:href`
* `//gmd:identificationInfo/gmd:descriptiveKeywords//gmd:type/gmd:MD_KeywordTypeCode`
* `//gmd:identificationInfo/gmd:descriptiveKeywords//gmd:keyword/gco:CharacterString`

=== What is being measured

The presence of all `gmd:MD_Keywords/gmd:keyword` elements with the appropriate
`gmd:thesaurus` and `gmd:thesaurusName are checked that they contain a valid
WIGOS station identifier.

=== Rationale for measurement

Valid WIGOS station identifiers provide a reference to authoritative station
information in WMO OSCAR.

=== Rules for implementation

.Valid station identifier implementation rules
|===
|Rule |Score

|test for a valid thesaurus
|1

|test for a valid keyword type code of type `place`
|1

|test for the proper structure of a WIGOS identifier
(`<WIGOS Identifier Series (number)>-<Issuer of Identifier (number)>-<Issue Number (number)>-<Local Identifier (characters)`)
|1

|test that 50 percent of WIGOS identifiers exist in WMO OSCAR
|1

|test that 80 percent of WIGOS identifiers exist in WMO OSCAR
|1

|test that 100 percent of WIGOS identifiers exist in WMO OSCAR
|1

|===

Total possible score: 6

=== Score values

.Valid station identifier score values
|===
|Rank | Score

|Low
|0 - 1

|Medium
|2-4

|High
|5-6
|===

=== Guidance to score well on this assessment

```xml
<gmd:MD_Keywords>
  <gmd:descriptiveKeywords>
    <gmd:keyword>
      <gco:CharacterString>http://wis.wmo.int/WMOVolumeAGazeteer.xml#71966</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_KeywordTypeCode" codeListValue="place" codeSpace="ISOTC211/19115">place</gmd:MD_KeywordTypeCode>
    </gmd:type>
    <gmd:thesaurusName xlink:type="simple" xlink:title="WMO Publication No. 9, Volume A, Observing Stations and WMO Catalogue of Radiosondes" xlink:href="http://www.wmo.int/pages/prog/www/ois/volume-a/vola-home.htm" />
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```
