
== D. Valid Station Identifier

See: related KANBAN card: https://github.com/wmo-im/wmcp/issues/20

A station id, when provided, should be a WIGOS identifier long version, ie:
https://oscar.wmo.int/surface//index.html#/search/station/stationReportDetails/0-20000-0-10505

And when a station identifier is provided then it should be a VALID WIGOS
identifier url. This can be verified

=== To which WMCP element(s) does it apply?

The stationID should be defined as a Keyword type "place".

=== What is being measured?

* Detect old stations id (ACTION: still define how), and recommend to have them replaced by the WIGOS station ID.
* When a WIGOS ID is provided, check that it is the correct format.
* When a WIGOS ID is provided, check that it is a valid one. 
* Check that the Thesaurus element is used, and that the correct Thesaurus title is used.


=== Why should we measure it?

=== How is the measurement executed?

=== What is (are) considered valid results?

=== Guidance to score well on this assessment

Update the guidance to explain where to put the station information

