== E. Temporal information

Metadata records should contain the following temporal information:

. Temporal extent: This element describes the period of time that the available product covers.
. Data Update frequency: The temporal frequency at which the data is updated (ie, every x hours, days, ...).

=== Status

Draft

=== WCMP Element(s)

* `/gmd:MD_Metadata/gmd:identification//gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent`
* `/gmd:MD_Metadata/gmd:identification//gmd:resourceMaintenance//gmd:maintenanceAndUpdateFrequency`

=== What is being measured

The presence of a correctly defined temporal extent and data update frequency.

=== Rationale for measurement

Temporal information is a significant characteristic of weather/climate/water
data and as such is critical for users to know which period(s) of time is/are
covered by products and how often new products are received.

=== Rules for implementation

The TemporalExtent is present in `gmd:temporalElement` with the xpath `//gmd:MD_Metadata/gmd:identificationInfo//gmd:extent//gmd:temporalElement/*/gmd:extent/`:

```xml
<gmd:identificationInfo>
  ...
  <gmd:temporalElement>
    <gmd:EX_TemporalExtent id="boundingTemporalExtent">
      <gmd:extent>
        <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
          <gml:beginPosition>2005-10-01</gml:beginPosition>
          <gml:endPosition>2014-10-20</gml:endPosition>
        </gml:TimePeriod>
      </gmd:extent>
    </gmd:EX_TemporalExtent>
  </gmd:temporalElement>
  ...
</gmd:identificationInfo>
```

The Data Update Frequency is present in 'gmd:maintenanceAndUpdateFrequency' with the xpath '//gmd:MD_Metadata/gmd:identificationInfo/*/gmd:resourceMaintenance/*/gmd:maintenanceAndUpdateFrequency':

```xml
<gmd:identificationInfo>
  ...
  <gmd:resourceMaintenance>
    <gmd:MD_MaintenanceInformation>
      <gmd:maintenanceAndUpdateFrequency>
        <gmd:MD_MaintenanceFrequencyCode codeListValue="irregular" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_MaintenanceFrequencyCode"/>
      </gmd:maintenanceAndUpdateFrequency>
      <gmd:userDefinedMaintenanceFrequency>
        <gts:TM_PeriodDuration>PT6H</gts:TM_PeriodDuration>
      </gmd:userDefinedMaintenanceFrequency>
      <gmd:maintenanceNote>
        <!-- DRAFT – Guidance on WIS Discovery Metadata (following CBS-16), p38 -->
        <gco:CharacterString>Instances of bulletin SIKB20NGTT are available every 6 hours starting at 03 UTC.</gco:CharacterString>
      </gmd:maintenanceNote>
    </gmd:MD_MaintenanceInformation>
  </gmd:resourceMaintenance>
  ...
</gmd:identificationInfo>
```

.Temporal information implementation rules
|===
|Rule |Score

|The Temporal Extent is not present
|-1

|The Temportal Extent is present and well formatted (with a begin and an end)
|+1

|The Data Update Frequency is not present
|-1

|The Data Update Frequency is present and well formatted 
|+1
|===

Total possible score: 2 (100%)

=== Guidance to score well on this assessment

Ensure that the Temporal Extent and the Update Frequency is present in the metadata record.
