
== E. Temporal information

Metadata records should contain the following temporal information:

. Temporal extent: This element describes the period of time that the available product covers.
. Data Update frequency: The temporal frequency at which the data is updated (ie, every x hours, days, ...).

=== E.1 WMCP Elements

the TemporalExtent is present in `gmd:temporalElement` with the xpath , `//gmd:MD_Metadata/gmd:identificationInfo/*/ gmd:extent/*/gmd:temporalElement/*/gmd:extent/`

....
<gmd:temporalElement>
   <gmd:EX_TemporalExtent id="boundingTemporalExtent">
     <gmd:extent>
       <gml:TimePeriod gml:id="boundingTemporalExtentPeriod">
       <gml:beginPosition>2005-10-01</gml:beginPosition>
       <gml:endPosition>2014-10-20</gml:endPosition>
       </gml:TimePeriod>
     </gmd:extent>
   </gmd:EX_TemporalExtent>
</gmd:temporalElement>
....

The Data Update Frequency is present in 'gmd:maintenanceAndUpdateFrequency' with the xpath, '//gmd:MD_Metadata/gmd:identificationInfo/*/gmd:resourceMaintenance/*/gmd:mainte
nanceAndUpdateFrequency'

....
<gmd:resourceMaintenance>
  <gmd:MD_MaintenanceInformation>
    <gmd:maintenanceAndUpdateFrequency>
     <gmd:MD_MaintenanceFrequencyCode codeListValue="irregular"
      codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodel     ists.xml#MD_MaintenanceFrequencyCode"/>
     </gmd:maintenanceAndUpdateFrequency>
    <gmd:userDefinedMaintenanceFrequency>
      <gts:TM_PeriodDuration>PT6H</gts:TM_PeriodDuration>
    </gmd:userDefinedMaintenanceFrequency>
    <gmd:maintenanceNote>
DRAFT – Guidance on WIS Discovery Metadata (following CBS-16), p38
    <gco:CharacterString>Instances of bulletin SIKB20NGTT are available every 6 hours starting at 03 UTC.</gco:CharacterString>
    </gmd:maintenanceNote>
 </gmd:MD_MaintenanceInformation>
</gmd:resourceMaintenance>
....

=== E.2 What is being measured

The present of a correctly defined TemporalExtent and Data Update Frequency is measured.

=== E.3 Rationale for measurement

This is a very import information for qualifying the product described by a metadata record even if it is optional in the WMCP 1.3 standard.
It is very crucial for users to which period of time is covered by the products and how often a new product is received.

=== E.4 Rules for implementation

|===
|Rule |Score

|The Temporal Extent is not present
|-5

|The Temportal Extent is present and well formatted (with a begin and an end)
|+5

|The Data Update Frequency is not present
|-5

|The Data Update Frequency is present and well formatted 
|+5
|===

=== E.5 Score values

.Temporal information score value
|===
|Rank | Score

|Low
|0

|Medium
|5

|High
|10
|===

=== Guidance to score well on this assessment

Ensure that the Temporal Extent and the Update Frequency is present in the metadata record.

==== E.3 Bulletin metadata availability

A Bulletin should contain a temporal extent with begin end and a period for indicating how long the data is kept on the cache (24 hr).
It should also probably be repeated in the abstract.

