== F. WMOEssential data links

=== Status

Draft

=== WMCP element(s)

* `/gmd:MD_Metadata/gmd:identificationInfo//gmd:resourceConstraints/gmd:MD_LegalConstaints/gmd:otherConstraints`
* `/gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage`

=== What is being measured

Whether the DataLicenseCode of `WMOEssential` is provided as a constraint as
part of data identification, if yes then ensure that distribution URLs are
provided.

=== Rationale for measurement

All `WMOEssential` data should have 1..n distribution links to the data.

=== Rules for implementation

```xml
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <gmd:accessConstraints>
      <gmd:MD_RestrictionCode codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_RestrictionCode" codeListValue="none" codeSpace="ISOTC211/19115">none</gmd:MD_RestrictionCode>
    </gmd:accessConstraints>
    <gmd:otherConstraints>
      <gco:CharacterString>WMOEssential</gco:CharacterString>
    </gmd:otherConstraints>
    <gmd:otherConstraints>
      <gco:CharacterString>GTSPriority2</gco:CharacterString>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
```
  
```xml
<gmd:MD_DigitalTransferOptions>
  <gmd:onLine>
    <gmd:CI_OnlineResource>
      <gmd:linkage>
        <gmd:URL>https://opendata.dwd.de/weather/wmc/icon-eps/data/grib</gmd:URL>
      </gmd:linkage>
      <gmd:protocol>
        <gco:CharacterString>http</gco:CharacterString>
      </gmd:protocol>
      <gmd:name>
        <gco:CharacterString>GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:name>
      <gmd:description>
        <gco:CharacterString>WMO Information System, download products/data through GISC Offenbach, Deutscher Wetterdienst</gco:CharacterString>
      </gmd:description>
    </gmd:CI_OnlineResource>
  </gmd:onLine>
</gmd:MD_DigitalTransferOptions>
```

.WMOEssential data links implementation rules
|===
|Rule |Score

|DataLicenseCode is `WMOEssential` and 1..n valid distribution links are provided
|1

|DataLicenseCode is `WMOEssential` and 1..n invalid distribution links are provided
|-1
|===

Total possible score: 1 (100%)

=== Guidance to score well on this assessment

If your data described in your metadata is categorized as `WMOEssential`,
provide a valid link to the data.
