
== I. GraphicOverview for non bulletins metadata records

A thumbnail preview image for each available products improves greatly the user experience, allowing the user to recognise or understand by just looking at the thumbnail image, the product she is looking at in the search results. It makes also the WIS portals more user friendly and attractive to the users.

Examples of catalogues using such information are here:

- https://gisc.dwd.de[GISC DWD]

- https://navigator.eumetsat.int/search?query=MSG%20RGB[EUMETSAT Product Navigator]


=== I.1 To which WMCP element(s) does it apply ?

This KPI applies to //<gmd:identificationInfo>/<gmd:MD_DataIdentification>/<gmd:graphicOverview>/<gmd:MD_BrowseGraphic/<gmd:fileName>

....
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
     <gmd:fileName>
        <gco:CharacterString>https://navigator.eumetsat.int/preview/meteosat-msg_naturalenhncd.jpg</gco:CharacterString>
     </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
....

=== I.2 What is being measured and why should it be measured

The presence of the <gmd:graphicOverview> is verified and it is checked that it contains a url to a JPG or PNG Image

It should be measured because it contributes to the corresponding product information in the WIS catalogues and make them much more informative and user friendly by showing to the users an overview of the discovered products. It can be showed in the product overview or in the search results list.

=== I.3 KPI implementation rules 

This part defines how a program should verify the currently described KPI.

....
result = False
url    = None

if xpath(//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:filename/gmx:Anchor/@xlink:href) then
  
  url = xpath.extract(//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:filename/gmx:Anchor/@xlink:href)

elif xpath(//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:filename/gco:CharacterString) them

  url = xpath.extract(//gmd:identificationInfo/gmd:MD_DataIdentification/gmd:graphicOverview/gmd:MD_BrowseGraphic/gmd:filename/gco:CharacterString)

fi

if url then

  //resolve the url to download the image (redirect have to be followed)
  download the image and check that the downloaded content starts the the JPG or PNG magic number.
  
  result = True
fi

return result
....
  
=== I.4 Score Values

To be defined.

=== I.5 Guidance to score well on this assessment

In addition to the presence of the file it would be good to define a typical size (800x800 pixels for instance) such that all images are normalized.
