
== I. GraphicOverview for non bulletins metadata records

A thumbnail preview image for each available products improves greatly the user experience, allowing the user to recognise or understand by just looking at the thumbnail image, the product she is looking at in the search results. It makes also the WIS portals more user friendly and attractive to the users.

Examples of catalogues using such information are here:

- https://gisc.dwd.de[GISC DWD]

- https://navigator.eumetsat.int/search?query=MSG%20RGB[EUMETSAT Product Navigator]


=== I.1 To which WMCP element(s) does it apply ?

This KPI applies to //<gmd:identificationInfo>/<gmd:MD_DataIdentification>/<gmd:graphicOverview>/<gmd:MD_BrowseGraphic/<gmd:fileName>

....
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
     <gmd:fileName>
        <gco:CharacterString>https://navigator.eumetsat.int/preview/meteosat-msg_naturalenhncd.jpg</gco:CharacterString>
     </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
....

=== I.2 What is being measured ?

The presence of that information (<gmd:graphicOverview>) is measured and can contribute to an overall quality score.

=== I.3 Why should it be measured ?

It should be measured because it contributes to the corresponding product information in the WIS catalogues and make them much more informative and user friendly by showing to the users an overview of the discovered products. It can be showed in the product overview or in the search results list.

=== I.4 How is the measurement executed ?

A program can get the entire list of metadata records from the OAI-PMH interface of the GISC catalogues and check for the presence of the <gmd:graphicOverview> in the individual records. That could be one rule defined and verified against each individual records and leading to the production of a quality report available from the web.

=== I.5 What is (are) considered valid results?

The presence of a link to a valid image file (that should be verified as well)

=== I.6 Guidance to score well on this assessment

In addition to the presence of the file it would be good to define a typical size (800x800 pixels for instance) such that all images are normalized.
