== J. Links health

=== WMCP element(s)

Any element content with linked information (URLs). Links are generally
present in `gmd:onlineResource`, `gmd:graphicOverview`, and `gmx:Anchor/@xlink:href`.

```xml
<gmd:CI_OnlineResource>
   <gmd:linkage>
      <gmd:URL>https://eumetview.eumetsat.int/mapviewer/?product=EO:EUM:DAT:MSG:SNOW</gmd:URL>
   </gmd:linkage>
</gmd:CI_OnlineResource>
```

```xml
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
    <gmd:fileName>
      <gco:CharacterString>https://navigator.eumetsat.int/preview/0deg-snow.jpg</gco:CharacterString>
    </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

=== What is being measured

The number of broken links in each individual metadata record.  Broken links
include links which, when accessed, result in a 4xx or 5xx HTTP error.footnote:[https://httpstatuses.com].

Also being measured is the use of HTTPS as the link protocol throughout WIS Metadata..

=== Rationale for measurement

Broken links damage the user experience and gives the impression to users that
a website is not maintained (88% of the online consumers are less likely to
return to a site after a bad experience.footnote:[https://review42.com/web-design-statistics]).
In addition, having numerous broken links affects the reputation and rank of
your website when indexed by mass market search engines.

HTTPS is increasingly becoming a requirement for numerous agencies as well as the
suggested protocol vs. HTTP.  Having non-HTTPS links in a WCMP document often leads to mixed
content errors in web applications deployed via HTTPS for example, and using AJAX/XHR design
patterns.  HTTPS supports secure, authoritative and trustworthy links as part of WIS Metadata and WIS.

=== Rules for implementation

.Links health implementation rules
|===
|Rule |Score

|Document has 1 or more broken links
|0

|Document has 1 - 3 accessible links
|2

|Document has 4 - 6 accessible links
|5

|Document has over 6 accessible links
|8

|Document links are available as HTTPs with a valid SSL certificate
|2
|===

=== Score values

.Links health score values
|===
|Rank | Score

|Low
|0

|Medium
|5

|High
|10
|===

=== Guidance to score well on this assessment

Ensure that all links resolve and are accessible via HTTPS.
