== J. Broken links

=== WMCP element(s)

Any element content with linked informations (URLs). Links are generally
present in `<gmd:onlineResource>`, `<gmd:graphicOverview>`, 

```xml
<gmd:CI_OnlineResource>
   <gmd:linkage>
      <gmd:URL>https://eumetview.eumetsat.int/mapviewer/?product=EO:EUM:DAT:MSG:SNOW</gmd:URL>
   </gmd:linkage>
</gmd:CI_OnlineResource>
```

```xml
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
    <gmd:fileName>
      <gco:CharacterString>https://navigator.eumetsat.int/preview/0deg-snow.jpg</gco:CharacterString>
    </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

=== What is being measured

The number of broken links in each individual metadata record.  Broken links
include links which, when accessed, result in a 4xx or 5xx HTTP error.footnote:[https://httpstatuses.com].

=== Rationale for measurement

Broken links damage the user experience and gives the impression to users that
a website is not maintained (88% of the online consumers are less likely to
return to a site after a bad experience.footnote:[https://review42.com/web-design-statistics]).
In addition, having numerous broken links affects the reputation and rank of
your website when indexed by mass market search engines.

=== Rules for implementation

.Broken links implementation rules
|===
|Rule |Score

|Document has 1 or more broken links
|0

|Document has 1 -3 accessible links
|5

|Document has over 3 accessible links
|10
|===

=== Score values

.Broken links score values
|===
|Rank | Score

|Low
|0

|Medium
|5

|High
|10
|===

=== Guidance to score well on this assessment

Ensure that all links resolve and are accessible.
