== J. Links health

=== Status

Draft

=== WMCP element(s)

Any element or attribute content with linked information (URLs). Links are
generally present in `gmd:URL`, `gmd:graphicOverview`, `gmx:Anchor/@xlink:href`,
and `@codeList` elements/attributes.

```xml
<gmd:CI_OnlineResource>
   <gmd:linkage>
      <gmd:URL>https://eumetview.eumetsat.int/mapviewer/?product=EO:EUM:DAT:MSG:SNOW</gmd:URL>
   </gmd:linkage>
</gmd:CI_OnlineResource>
```

```xml
<gmd:graphicOverview>
  <gmd:MD_BrowseGraphic>
    <gmd:fileName>
      <gco:CharacterString>https://navigator.eumetsat.int/preview/0deg-snow.jpg</gco:CharacterString>
    </gmd:fileName>
  </gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```

```xml
<gmd:MD_Identifier>
  <gmd:code>
    <gmx:Anchor xlink:actuate="onRequest" xlink:href="https://dx.doi.org/10.14287/10000004" xlink:title="DOI">doi:10.14287/10000004</gmx:Anchor>
  </gmd:code>
</gmd:MD_Identifier>
```

```xml
<gmd:dateType>
  <gmd:CI_DateTypeCode codeList="http://wis.wmo.int/2011/schemata/iso19139_2007/schema/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision" codeSpace="ISOTC211/19115">revision</gmd:CI_DateTypeCode>
</gmd:dateType>
```

=== What is being measured

The number of broken links in each individual metadata record.  Broken links
include links which, when accessed, result in a 4xx or 5xx HTTP error.footnote:[https://httpstatuses.com].

Also being measured is the use of HTTPS (with a valid SSL certificate) as the
link protocol throughout WIS Metadata.

=== Rationale for measurement

Broken links damage the user experience and gives the impression to users that
a website is not maintained (88% of the online consumers are less likely to
return to a site after a bad experience.footnote:[https://review42.com/web-design-statistics]).
In addition, having numerous broken links affects the reputation and rank of
your website when indexed by mass market search engines.

HTTPS is increasingly becoming a requirement for numerous agencies as well as the
suggested protocol vs. HTTP.  Having non-HTTPS links in a WCMP document often leads to mixed
content errors in web applications deployed via HTTPS for example, and using AJAX/XHR design
patterns.  HTTPS supports secure, authoritative and trustworthy links as part of WIS Metadata.

=== Rules for implementation

.Links health implementation rules
|===
|Rule |Score

|Each valid link provided
|1
|Each valid HTTPS link provided
|1
|===

Total possible score: (valid links + valid HTTPS links) / (total links * 2) (100%)

=== Guidance to score well on this assessment

Ensure that all links resolve and are accessible via HTTPS.
