== K. Data Policy Possible combination

Data parameter keywords are optional elements syntactically.  An xml record will validate without its presence.


=== K.1 To which WCMP element(s) does it apply ?

The data policy information is expressed via means of resourceContrains and scope of distribution:

    the *resourceConstraints* part, which contains the data policy information; and
    the *scope of distribution* part: using one of the terms: 'GlobalExchange', 'RegionalExchange' or 'OriginatingCentre' (to be inserted as a  keyword).

==== K.1.1 Publicly and unrestricted data not distributed via GTS:

Q: Would this be applicable to Open Data?

....
<!-- Resource Constrains for Publicly and unrestricted data  -->
<gmd:resourceConstraints>
  <gmd:MD_LegalConstraints>
    <!--  add useLimitation with ..No conditions apply..  -->
    <gmd:useLimitation>
      <gco:CharacterString>No conditions apply</gco:CharacterString>
    </gmd:useLimitation>
    <gmd:useConstraints>
      <!--  Restriction code have to point to WMOCodeLists.xml -->
<gmd:MD_RestrictionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#MD_RestrictionCode"
         codeListValue="otherRestrictions">otherRestrictions</gmd:MD_RestrictionCode>
    </gmd:useConstraints>
    <!--  otherConstraints with ..NoLimitation..  -->
    <gmd:otherConstraints>
      <gco:CharacterString>NoLimitation</gco:CharacterString>
    </gmd:otherConstraints>
  </gmd:MD_LegalConstraints>
</gmd:resourceConstraints>
 
<!-- Scope of distribution for non GTS products: OriginatingCentre -->
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <!--  keyword OriginatingCentre applies for DCPC Data -->
      <gco:CharacterString>OriginatingCentre</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode
           codeList="http://wis.wmo.int/2012/codelists/WMOCodeLists.xml#MD_DistributionScopeCode"
           codeListValue="dataCentre">dataCentre</gmd:MD_KeywordTypeCode>
    </gmd:type>
    <gmd:thesaurusName>
            <gmd:CI_Citation>
                <gmd:title>
                    <gco:CharacterString>WMO_DistributionScopeCode [http://wis.wmo.int/2012/codelists/WMOCodeLists.xml]</gco:CharacterString>
                </gmd:title>
                <gmd:date>
                    <gmd:CI_Date>
                        <gmd:date>
                            <gco:Date>2012-06-27</gco:Date>
                        </gmd:date>
                        <gmd:dateType>
                            <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision">revision</gmd:CI_DateTypeCode>
                        </gmd:dateType>
                    </gmd:CI_Date>
                </gmd:date>
            </gmd:CI_Citation>
    </gmd:thesaurusName>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
....

=== K.2 What is being measured ?

The presence of a Data Policy with the conditions of use that apply to the represented dataset and the presence of scope of distribution

=== K.3 Why should it be measured ?

Users need to know the conditions of use of a particular dataset before accessing the data

Q: The guidelines mention that is is only mandatory for GTS data.   This should be mandatory for every xml record.

Conditional.  Mandatory for WMO Core Profile 1.3, for GTS data.

=== K.4 How is the measurement executed ?

A program would need to check the presence of gmd:resourceConstraints

Q: It would be difficult to measure publicly unsrestricted datasets with otherRestrictions, can we extend MD_RestrictionCode in WMOCodeList to include public ?

=== K.5 What is (are) considered valid results?



=== K.6 Guidance to score well on this assessment




