== L. Distribution information

Metadata records should contain information regarding how to access the data
which it is describing.

=== WMCP element(s)

* `//gmd:MD_Metadata/gmd:distributionInfo`

```xml
<gmd:distributionInfo>
  <gmd:MD_Distribution>
    <gmd:distributionFormat>
      <gmd:MD_Format>
        <gmd:name>
          <gco:CharacterString>GRIB</gco:CharacterString>
        </gmd:name>
        <gmd:version>
          <gco:CharacterString>FM 92 GRIB Edition 2</gco:CharacterString>
        </gmd:version>
        <gmd:specification>
          <gco:CharacterString>http://www.wmo.int/pages/prog/www/WMOCodes.html</gco:CharacterString>
        </gmd:specification>
      </gmd:MD_Format>
    </gmd:distributionFormat>
    <gmd:transferOptions>
      <gmd:MD_DigitalTransferOptions>
        <gmd:onLine>
          <gmd:CI_OnlineResource>
            <gmd:linkage>
              <gmd:URL>ftp://data-portal.ecmwf.int</gmd:URL>
            </gmd:linkage>
            <gmd:protocol>
              <gco:CharacterString>WWW:DOWNLOAD-1.0-ftp--download</gco:CharacterString>
            </gmd:protocol>
            <gmd:name>
              <gco:CharacterString>ECMWF DCPC FTP Server</gco:CharacterString>
            </gmd:name>
            <gmd:description>
              <gco:CharacterString>WMO Information System download service through ECMWF</gco:CharacterString>
            </gmd:description>
            <gmd:function>
              <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="download">
            </gmd:function>
          </gmd:CI_OnlineResource>
        </gmd:onLine>
      </gmd:MD_DigitalTransferOptions>
    </gmd:transferOptions>
  </gmd:MD_Distribution>
</gmd:distributionInfo>
```

=== What is being measured

The presence of distribution information as well supporting elements.

* format (`//gmd:MD_Metadata/gmd:distributionInfo/*/gmd:distributionFormat`).
  That can rely on existing WMO supported formats
* transferOptions (`//gmd:MD_Metadata/gmd:distributionInfo/*/gmd:transferOptions//gmd:onLine`),
  including a `gmd:linkage` with a URL to access the service providing the data
* distributor contact information
 
=== Rationale for measurement

Distribution information provides the necessary information for accessing the
data, supported formats, and contact inforamtion for the data distributor.

=== Rules for implementation

By detecting the presence of the distribution format and transferOptions
(multiple options are possible). See page 35 of the WMO Core Profile Metadata
Guidance.

.Distribution information implementation rules
|===
|Rule |Score

|format is identified
|1

|1..n transfer options are identified
|1

|distributor contact is identified
|1
|===

Total possible score: 3

=== Score values

.Distribution information score values
|===
|Rank | Score

|Low
|0

|Medium
|1 - 2

|High
|3

|===

=== Guidance to score well on this assessment

Always add format/medium information, 1..n links as well as a distributor
contact. Note that a distributor contact would not have to be the same as
the main point of contact, principal investigator.
