== L. Distribution information

Metadata records should contain information regarding how to access the data
which it is describing.

=== Status

Draft

=== WMCP element(s)

* `//gmd:distributionInfo//gmd:distributionFormat/gmd:MD_Format`
* `//gmd:distributionInfo//gmd:MD_DigitalTransferOptions//gmd:onLine//gmd:URL`
* `//gmd:distributionInfo//gmd:MD_Distributor//gmd:organisationName`
* `//gmd:distributionInfo//gmd:MD_Distributor//gmd:contactInfo//gmd:electronicMailAddress/gco:CharacterString`


```xml
<gmd:distributionInfo>
  <gmd:MD_Distribution>
    <gmd:distributionFormat>
      <gmd:MD_Format>
        <gmd:name>
          <gco:CharacterString>FM 94 (BUFR)</gco:CharacterString>
        </gmd:name>
        <gmd:version>
          <gco:CharacterString>XII EXT.</gco:CharacterString>
        </gmd:version>
        <gmd:specification>
          <gmx:Anchor xlink:title="FM 94 (BUFR)" xlink:href="https://www.wmo.int/pages/prog/www/WMOCodes.html">FM 94 (BUFR)</gmx:Anchor>
        </gmd:specification>
      </gmd:MD_Format>
    </gmd:distributionFormat>
    <gmd:distributor>
      <gmd:MD_Distributor>
        <gmd:distributorContact>
          <gmd:CI_ResponsibleParty>
            <gmd:individualName>
              <gco:CharacterString>DT/DSI/OP/TEL</gco:CharacterString>
            </gmd:individualName>
            <gmd:organisationName>
              <gco:CharacterString>NMC FRANCE - Météo-France</gco:CharacterString>
            </gmd:organisationName>
            <gmd:contactInfo>
              <gmd:CI_Contact>
                <gmd:phone/>
                <gmd:address>
                  <gmd:CI_Address>
                    <gmd:deliveryPoint>
                      <gco:CharacterString>Direction des Systèmes d'Information, 42 avenue Gaspard CORIOLIS</gco:CharacterString>
                    </gmd:deliveryPoint>
                    <gmd:city>
                      <gco:CharacterString>TOULOUSE</gco:CharacterString>
                    </gmd:city>
                    <gmd:postalCode>
                      <gco:CharacterString>31057</gco:CharacterString>
                    </gmd:postalCode>
                    <gmd:country>
                      <gco:CharacterString>France</gco:CharacterString>
                    </gmd:country>
                    <gmd:electronicMailAddress>
                      <gco:CharacterString>gisc_support@meteo.fr</gco:CharacterString>
                    </gmd:electronicMailAddress>
                  </gmd:CI_Address>
                </gmd:address>
                <gmd:onlineResource>
                  <gmd:CI_OnlineResource>
                    <gmd:linkage>
                      <gmd:URL>http://www.meteo.fr</gmd:URL>
                    </gmd:linkage>
                  </gmd:CI_OnlineResource>
                </gmd:onlineResource>
              </gmd:CI_Contact>
            </gmd:contactInfo>
            <gmd:role>
              <gmd:CI_RoleCode codeListValue="pointOfContact" codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/gmxCodelists.xml#CI_RoleCode">pointOfContact</gmd:CI_RoleCode>
            </gmd:role>
          </gmd:CI_ResponsibleParty>
        </gmd:distributorContact>
      </gmd:MD_Distributor>
    </gmd:distributor>
    <gmd:transferOptions>
      <gmd:MD_DigitalTransferOptions>
        <gmd:onLine>
          <gmd:CI_OnlineResource>
            <gmd:linkage>
              <gmd:URL>http://wispi.meteo.fr/openwis-user-portal/srv/en/main.home?urn=urn:x-wmo:md:int.wmo.wis::ISMN10LFPW</gmd:URL>
            </gmd:linkage>
            <gmd:protocol>
              <gco:CharacterString>WWW:LINK-1.0-http--link</gco:CharacterString>
            </gmd:protocol>
            <gmd:name>
              <gco:CharacterString>Permanent link</gco:CharacterString>
            </gmd:name>
            <gmd:description>
              <gco:CharacterString>GISC Toulouse</gco:CharacterString>
            </gmd:description>
          </gmd:CI_OnlineResource>
        </gmd:onLine>
      </gmd:MD_DigitalTransferOptions>
    </gmd:transferOptions>
  </gmd:MD_Distribution>
</gmd:distributionInfo>
```

=== What is being measured

The presence of distribution information and supporting elements.

* format (`//gmd:distributionInfo//gmd:distributionFormat/gmd:MD_Format`)
  That can rely on existing WMO supported formats
* 1..n `gmd:transferOptions` (`//gmd:distributionInfo/*/gmd:transferOptions//gmd:onLine`),
  including a `gmd:linkage` with a URL to access the data
* distributor contact information (organization, email)
 
=== Rationale for measurement

Distribution information provides the necessary information for accessing the
data, supported formats, and contact information for the data distributor.

=== Rules for implementation

By detecting the presence of the distribution format and transferOptions
(multiple options are possible). See page 35 of the WMO Core Profile Metadata
Guidance.

.Distribution information implementation rules
[cols="1a,2"]
|===
|Rule |Score

|`MD_Format` is defined
|1

|format specification has an Anchor with a resolvable HTTP URI 
|1

|distributor contact organization is defined
|1

|distributor contact email is defined
|1

|1..n transfer options are defined
|1

|===

Total possible score: 5 (100%)

=== Guidance to score well on this assessment

. Always add format/medium information, a link to the format specification,
  1..n transfer options as well as a distributor contact. Note that a
  distributor contact does not have to be the same as the main point of
  contact, principal investigator
. Always provide an email for the distributor
