=== N.1 To which WMCP element(s) does it apply ?

This KPI applies to all the elements defining some information regarding the metadata content attribution:
Responsible party as creator or publisher, publication year and DOI.


=== N.3 KPI implementation rules 

This part defines how a program should verify the currently described KPI.

....
contributing_score = 0

if xpath(//gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:citedResponsibleParty/gmd:CI_ResponsibleParty[gmd:role/gmd:CI_RoleCode/@codeListValue[(.)= 'resourceProvider' or (.) = 'originator' or (.) = 'principalInvestigator' or (.) = 'author' or (.) = 'collaborator']]) then
  
  contributing_score += 1 
fi

if xpath(//gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:citedResponsibleParty/gmd:CI_ResponsibleParty[.//gmd:role/gmd:CI_RoleCode/@codeListValue='publisher']) then
  
  contributing_score += 1 
fi

if xpath(//gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/[.//gmd:dateType/gmd:CI_DateTypeCode/@codeListValue = 'publication' or .//gmd:dateType/gmd:CI_DateTypeCode/@codeListValue = 'creation']) then

  contributing_score += 1 

fi

if xpath(	//gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:identifier/gmd:MD_Identifier/gmd:code[contains(., 'DOI') or contains(.,'doi') or contains(.,'Doi')]) then

  contributing_score += 1 

fi

return contributing_score
....
  
=== N.4 Score Values

To be defined. The points provided for that information should be "bonus" or optional points.

=== N.5 Guidance to score well on this assessment

A DOI with the associated creator/publisher and publication year information should be provided.
